### ISSUE TITLE
Border Noise Removal

### ISSUE THREAD

**Issue by xiaomaxiao** [tmbdev/ocropy#102]
"A Simple and Effective Approach for Border Noise Removal from Document Images"

The paper mentioned has been provided provided  an open source implementation of this method
as part of the OCRopus OCR system, but i can't  find it .

this is download link:
http://www.dfki.de/web/research/publications/renameFileForDownload?filename=Shafait-projection-based-cleanup-INMIC09.pdf&file_id=uploads_432

**Comment by amitdo** [comment]
It was part of OCRopus 0.4:
https://github.com/michaelyin/ocropus-git/blob/master/ocr-layout/ocr-pageframe-rast.h

**Comment by xiaomaxiao** [comment]
@amitdo Thanks too much

**Comment by amitdo** [comment]
Glad to help!

I suggest you to close this issue.
