### ISSUE TITLE
Add new tags for older releases

### ISSUE THREAD

**Issue by amitdo** [tmbdev/ocropy#116]
Hi @kba, @zuphilip :smile:

I suggest to add new tags for older releases:
0.5, 0.5.4, 0.6, 0.7
See: https://github.com/tmbdev/ocropy/wiki/Older-versions

I also suggest to remove these confusing tags and to add new tags instead:
classic-ocropy-0.1.1 => 0.7.2 / 0.8.1
classic-ocropy-0.1 => 0.7.1 / 0.8.0

**Comment by zuphilip** [comment]
I agree that the tags/versions number are quite confusing and some of them seems missing. Do such changes involve "push force" against the master branch?

Related issue: https://github.com/tmbdev/ocropy/issues/61

**Comment by stweil** [comment]
No, tagging can be done later at any time. You will need `git push --tags` to push local tags. Make sure you don't push tags used for local development.

**Comment by zuphilip** [comment]
@amitdo: How did you actually backdated the versions 0.5, 0.5.4, 0.6, 0.7 exactly? Are you sure there was a version 0.5.4?

**Comment by amitdo** [comment]
i had clones of the old hg repos. No longer have them...

>Are you sure there was a version 0.5.4?

Yes, Tom even announced it in the mailing list if I remember correctly.
There were also 0.5.1 - 0.5.3 tags.

**Comment by stweil** [comment]
@zuphilip, the [Wiki article](https://github.com/tmbdev/ocropy/wiki/Older-versions) contains all old versions and includes links to the exact commit of each version, so assigning tags is straight forward.

**Comment by zuphilip** [comment]
Yeah, I know that @amitdo collected these points in the wiki article, but the actual commit looks quite random for me. That is why I try to understand better, how he came up with this. Parts of the old hg repositories are archived, e.g. http://web.archive.org/web/20130703154319/http://code.google.com/p/ocropus/source/list and thereby we can see that there were indeed the tags inbetween:
![screenshot - oct 13 2016 8 11 am](https://cloud.githubusercontent.com/assets/5199995/19338354/c62eae9e-911c-11e6-9cf6-07e9538b95d1.png)
However, the commit history looks completely different to the commit history here. This confuses me very much...

**Comment by stweil** [comment]
https://github.com/sbuss/ocropus seems to be a git clone of that hg repository.

**Comment by amitdo** [comment]
Announcements from the mailing-list:
* 2007-10-23 [0.1](https://groups.google.com/forum/#!topic/ocropus/OYayNUjW2i8)
* 2007-12-14 [0.1.1](https://groups.google.com/forum/#!topic/ocropus/wfXQDMOmdi0)
* 2009-05-31 [0.4](https://groups.google.com/forum/#!topic/ocropus/TK9Xe-k1nHc)
* 2009-07-18 [0.4.1](https://groups.google.com/forum/#!topic/ocropus/KDV0sa8FUOU)
* 2009-07-21 [0.4.2](https://groups.google.com/forum/#!topic/ocropus/kNXRQkMAbz0)
* 2009-07-22 [0.4.3](https://groups.google.com/forum/#!topic/ocropus/8iz_Bkucg0g)
* 2012-06-03 [0.5](https://groups.google.com/forum/#!topic/ocropus/S73OMtJdVmw)
* 2012-07-16 [0.5.4](https://groups.google.com/forum/#!topic/ocropus/NbdtV_kh4Ms)
* 2012-08-18 [0.6pre1](https://groups.google.com/forum/#!topic/ocropus/rT6ju--MN-Q)
* 2012-08-23 [0.6](https://groups.google.com/forum/#!topic/ocropus/L-BJyrPcTYM)
* 2013-04-10  [0.7](https://groups.google.com/forum/#!topic/ocropus/Jpqz_Kc9M8g)

**Comment by amitdo** [comment]
In the google code hosting era the VCS was Mercurial (I think it started with svn). The commit hashes are different from those of git.
There was a top 'ocropus' repository with references to 'ocropy' and other sub-repos.

**Comment by zuphilip** [comment]
Okay, I changed the tag names (not the titles) for the classic ocorpus and added the tags of previous versions based on your information and the link of the hg-copy: https://github.com/tmbdev/ocropy/releases

**Comment by amitdo** [comment]
What about tagging the current code in master as 1.1?

**Comment by zuphilip** [comment]
Yeah, we should IMO start doing more frequently releases. My suggestion now is to tag `v1.1` as a release where the CLSTM training functionalities where fixed (commit https://github.com/tmbdev/ocropy/commit/e7f1a2d5c5a0c5d5e897225d4465062ebb11b6e1 looks suitable for that). [The remaining commits until now](https://github.com/tmbdev/ocropy/compare/v1.0...master) look more like bugfixing or cleanup work and could maybe be lead to several `v1.1.x`. What do you think? @kba @amitdo
