### ISSUE TITLE
ocropus-rpred `estrate` option throws exceptions

### ISSUE THREAD

**Issue by wallclock** [tmbdev/ocropy#121]
Got the following exception when `estrate` is used. 

Without `my-line.gt.txt`:
```
$ ocropus-rpred --estrate -m en-default.pyrnn.gz my-line.png 
INFO:  
INFO:  ########## /usr/local/bin/ocropus-rpred --estrate -m en-default.pyrnn.g
INFO:  
INFO:  #inputs1
# loading object en-default.pyrnn.gz
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rpred", line 289, in <module>
    print_info("%.5f"%(terr*1.0/total) + " " + terr+ " " + total + " " + args.model)
ZeroDivisionError: float division by zero
```

With `my-line.gt.txt`:
```
$ ocropus-rpred --estrate -m en-default.pyrnn.gz my-line.png 
INFO:  
INFO:  ########## /usr/local/bin/ocropus-rpred --estrate -m en-default.pyrnn.g
INFO:  
INFO:  #inputs1
# loading object en-default.pyrnn.gz
INFO:    6   6 my-line.png:I 5 $ 4 d L
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rpred", line 289, in <module>
    print_info("%.5f"%(terr*1.0/total) + " " + terr+ " " + total + " " + args.model)
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')
```

```
$ python --version
Python 2.7.12
```

**Comment by zuphilip** [comment]
This looks like a bug, also my error message looks a little different. Can you provide as your example (bin.png and gt.txt file)? What version of numpy are you using? You can find out by the following python commands:
```py
import numpy
numpy.version.version
```

**Comment by wallclock** [comment]
Here you go:
![output](https://cloud.githubusercontent.com/assets/20661570/19509316/c0010a64-9610-11e6-8912-5bf63062c211.png)
[output.gt.txt](https://github.com/tmbdev/ocropy/files/538204/output.gt.txt)
``` python
>>> import numpy
>>> numpy.version.version
'1.11.2'
```
Had the same issue with numpy 1.11.0 provided by ubuntu.

**Comment by zuphilip** [comment]
This issue will probably be solved by https://github.com/tmbdev/ocropy/pull/124.

**Comment by zuphilip** [comment]
Okay, that PR is now merged and it should solve this issue. @wallclock You can update to the newest version and test it again. Can you confirm that it is now working?

**Comment by wallclock** [comment]
Yes it is now working, thanks!

**Comment by tmbdev** [comment]
Note that the default model is not trained at all for handwriting.
