### ISSUE TITLE
UnicodeEncodeError in rtrain

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/ocropy#122]
```
root@7040af8be2dd:/ocropy# ./run-rtrain
+ tar -zxf tests/uw3-500.tgz
+ ocropus-rtrain 'book/*/*.bin.png' -d 5 -o uw3-500-model
# inputs 500
# tests None
# CenterNormalizer
# using default codec
# charset size 157 Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rtrain", line 143, in <module>
    print "["+"".join(charset)+"]"
UnicodeEncodeError: 'ascii' codec can't encode characters in position 96-155: or
dinal not in range(128)
```
Can someone reproduce this error? I don't understand what changed to earlier settings where I tried to train ocorpus... Currently, I am running [ocropus as a docker](https://github.com/kba/docker-ocropy) by @kba

**Comment by kba** [comment]
Could well be PYTHONIOENCODING again. I'll try a fix and rebuild the docker container.

**Comment by kba** [comment]
Yup, that's the problem.

**Comment by kba** [comment]
Once this https://hub.docker.com/r/kbai/ocropy/builds/brhnabakn6jwh5jxe6j8mmp/ is built (in ~ 10 minutes), please do `docker pull kbai/ocropy`.

**Comment by zuphilip** [comment]
Wow, that was fast. Yes, I can confirm it works now as expected. (The graphical option `-d` is not supported by docker, but without it the training is working.) Thank you very much!
