### ISSUE TITLE
'OCRopus File Formats' - Google Docs

### ISSUE THREAD

**Issue by amitdo** [tmbdev/ocropy#126]
https://docs.google.com/document/d/1czzhPZdQRs5vENwftHGt608BS1Y7Jj2f5ZZIkuSKP8A/preview

Only the first two are still relevant.

**Comment by zuphilip** [comment]
I copied the content into a new wiki site: https://github.com/tmbdev/ocropy/wiki/OCRopus-File-Formats and I even think that it is worth to document the not anymore used file formats.

**Comment by tmbdev** [comment]
All these formats are still used in some form (though not necessarily in the regular ocropy pipeline).

**Comment by kba** [comment]
Is the IUPR dokuwiki archived somewhere? There is a link to a page "external-file-formats" that sounds interesting ("the formats used by UW3, XDOC,").

**Comment by amitdo** [comment]
According to [this paper](http://www.madm.eu/_media/theses/ocropusgupta.pdf), the UW3 dataset uses a file format called [DAFS-B](https://www.google.co.il/search?q=%22DAFS%22+%22Document+Attribute+Format+Specification%22).

**Comment by kba** [comment]
XDOC:  http://kba.github.io/hocr-spec/1.2/#biblio-xdoc
