### ISSUE TITLE
What exactly is meant by 300 dpi for digital images

### ISSUE THREAD

**Issue by erikjalevik** [tmbdev/ocropy#134]
I am a little confused about the requirement that input images be 300 dpi, since dpi only makes sense when talking about printed hard copies of images.

I'm working with photos taken with smartphone cameras where this doesn't really apply.

Does it simply mean that images need to be at a reasonably high resolution? Or does it expect all images to be converted to 300 dpi first (without resampling) regardless of resolution?

**Comment by zuphilip** [comment]
I guess the standard use case for ocropus is digitization of books and thereby you should make sure that the scanning resolution is at least 300 dpi. Nowadays, smartphones have pretty good cameras and I guess that the picture from there should work without a problem (without any converting in advance). Maybe use the option `-n` if some plausibility checks fails.

**Comment by tmbdev** [comment]
The ocropy components will only work reasonably well for scanned 300 dpi images of printed text. Pictures taken with smartphones will not work well unless you preprocess them. Likewise, very high resolution scans (e.g., 1200dpi) won't work well. The checks are there to alert users to that.

**Comment by erikjalevik** [comment]
Thank you both for clarifying.

I'm getting reasonable results from smartphone photos at the moment, with some preprocessing. However, the nlbin tool does a pretty good job on its own for most of the preprocessing.

**Comment by zuphilip** [comment]
(Just some days ago I heard about an [interesting tool to enhance the resolution](https://github.com/alexjc/neural-enhance), which I wanted to try out, whether it influences the OCR recognition results...)

**Comment by kba** [comment]
@zuphilip How resizing with different [image scaling](https://en.wikipedia.org/wiki/Image_scaling) algorithms in general influence OCR results is something I'd like to investigate further too. I've seen that up-scaling low-res images can improve quality but not how different scaling algos perform. Maybe we can document this in the wiki, like [ImproveQuality](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality) in the tesseract wiki.

**Comment by ChillarAnand** [comment]
Can you tell me what should be the approximate image resolution?

**Comment by tmbdev** [comment]
People have reported good results with Waifu2x http://waifu2x.udp.jp/

It's best to scale images to 300dpi resolution, assuming you have standard size fonts (9pt to 14pt).

**Comment by zuphilip** [comment]
I added this information to the FAQ in the wiki: https://github.com/tmbdev/ocropy/wiki/FAQ#what-exactly-is-meant-by-300-dpi-for-digital-images
