### ISSUE TITLE
Use only one of lxml or BeautifulSoup

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/ocropy#147]
Currently, we are using both `lxml` and also `BeautifulSoup` in the a [requirements](https://github.com/tmbdev/ocropy/blob/master/requirements_1.txt) for `ocropy`. I found the following usage at the moment:
 * `lxml` is used in https://github.com/tmbdev/ocropy/blob/master/ocropus-gtedit
 * Standard output methods are used in https://github.com/tmbdev/ocropy/blob/master/ocrolib/hocr.py and https://github.com/tmbdev/ocropy/blob/master/ocropus-hocr
 * I couldn't find a statement `from bs4 import BeautifulSoup` or anything similar. Do we actually using that library at the moment?

It looks reasonable to use only one of these library, if possible. Any suggestions?

See also https://github.com/tmbdev/ocropy/pull/146#issuecomment-258786816

**Comment by amitdo** [comment]
https://github.com/tmbdev/ocropy/commit/10f8e92ed3c3

**Comment by kba** [comment]
Let's not require BeautifulSoup anymore.

**Comment by kba** [comment]
Also, why is Cython required?

**Comment by kba** [comment]
And imagemagick and curl in PACKAGES probably neither as far as I can see.

**Comment by kba** [comment]
numexpr was never used as far as I can see.

**Comment by kba** [comment]
Looks good, at least building and `./run-test` run fine with the reduced `requirements_1.txt`: https://circleci.com/gh/kba/ocropy/50

**Comment by kba** [comment]
This has been corrected, BeautifulSoup requirement and others dropped in #148.
