### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by PedroBarcha** [tmbdev/ocropy#153]
Hi there,
I've been studying ocropus for a while now, but I couldn't find it's thresholding, denoising and character recognition (not CLSTM) documentation. Does anyone know where to find it?
Thanks a lot.

**Comment by zuphilip** [comment]
This highly overlaps with the issue https://github.com/tmbdev/ocropy/issues/136.

**Comment by PedroBarcha** [comment]
@zuphilip I had already seen the wiki, as suggested in #136 . But it didn't help me at all. I was hoping to find at least the references to the algorithms, as you did in #118, when you mentioned the paper on layout analysis, that was extremely helpful. Do you know the articles on the matters I'm interested? Or at least any reference at all to the thresh/denoise/calssifier algorithms?

**Comment by zuphilip** [comment]
You can try to look at the publications wiki page: https://github.com/tmbdev/ocropy/wiki/Publications

**Comment by amitdo** [comment]
Thresholding - See [binarization](https://github.com/tmbdev/ocropy/wiki/Publications#binarization)
Denoising - I think it just removes small connected components.
Character recognition - Bidi-LSTM + CTC alignment. see the [ICDAR 2013 LSTM Tutorial](http://lstm.iupr.com/)
