### ISSUE TITLE
Port to Python3?

### ISSUE THREAD

**Issue by ChillarAnand** [tmbdev/ocropy#163]
ocropy doesn't seem to work with Python 3. Any plans on porting it?

**Comment by zuphilip** [comment]
There are several issues and PRs concerning this, just search here around.

It would certainly be nice to have a Python 3 compatible version but (as always) resources are short. (Maybe you also want to look at [kraken](https://github.com/mittagessen/kraken) which is a fork and mostly Python 3 compatible.)
