### ISSUE TITLE
Page numbers out of order after converting

### ISSUE THREAD

**Issue by jbins** [tmbdev/ocropy#164]
After using "ocrocis convert" to binarize my .tif images in my book/directory file (all images saved as 1.tif, 2.tif, 3.tif etc.) my images were spit out in a random order. Anyone know what I am doing wrong? Sorry for the rookie question...

**Comment by zuphilip** [comment]
You should ask that question maybe directly at the `ocrocis` repo: https://github.com/kaumanns/ocrocis . I don't know much about their CLI.

**Comment by jbins** [comment]
Oops! Sorry. Thank you for the help!

**Comment by zuphilip** [comment]
Cont'd in https://github.com/kaumanns/ocrocis/issues/2
