### ISSUE TITLE
Is it possible to parallelize training?

### ISSUE THREAD

**Issue by ChillarAnand** [tmbdev/ocropy#166]
Each sample is taking ~1 second to process. To train 100K samples it takes lot of time. If ocropus supports mutli threading/processing, training time will reduce drastically.

**Comment by zuphilip** [comment]
I cannot say anything about parallelization, but...

A faster training should be available with [CLSTM](https://github.com/tmbdev/clstm). Moreover, implementations relying more on GPU power (e.g. based on Tensorflow or Torch) are appearing as well.

**Comment by amitdo** [comment]
To benefit from the GPU speed with TF you need very expensive Nvidia card.

**Comment by zuphilip** [comment]
Add a new FAQ for this https://github.com/tmbdev/ocropy/wiki/FAQ#how-can-the-training-been-speed-up-is-it-possible-to-parallelize-the-trainig-or-to-use-gpu-power-for-training
