### ISSUE TITLE
Import statement in `nutils.py` (Scrutinizer bug)

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/ocropy#173]
The import statement on the [first line](https://github.com/tmbdev/ocropy/blob/master/ocrolib/nutils.py#L1) of `nutils.py` looks currently like this:
```py
from ocrolib.native import *
```
which leads for Scrutinizer to the message:
> The name `native` does not seem to exist in module `ocrolib`. 

What is the problem here and how can we solve it? Maybe this is also connected to [ocrolib/__init__.py](https://github.com/tmbdev/ocropy/blob/master/ocrolib/__init__.py).

**Comment by amitdo** [comment]
I guess 'Scrutinizer' is this service:
https://scrutinizer-ci.com/

**Comment by zuphilip** [comment]
Yes, here is the link to the results (maybe slightly outdated now): https://scrutinizer-ci.com/g/kba/ocropy/

**Comment by zuphilip** [comment]
We got rid of `nutils.py` overall in #274 and thereby the problem here was solved.
