### ISSUE TITLE
ocropus-rtrain broken

### ISSUE THREAD

**Issue by jze** [tmbdev/ocropy#178]
commit 7020a76 broke ocropus-rtrain. Error message is 
`TypeError:` sum() takes no keyword arguments`

commit 952910e works

**Comment by lunactic** [comment]
Just stumbled upon that as well. From what I can tell it seems that the standard sum() methods are called instead of the ones from numpy?

**Comment by zuphilip** [comment]
Hm.. I tested with the newest commit by running `./run-rtrain` and this seems to work fine.

Can you describe in more details how you did use the functions, such that I can reproduce the error here?

There was recently a commit which was normalizing the import statements https://github.com/tmbdev/ocropy/pull/154, which could maybe lead to something as described here...

**Comment by zuphilip** [comment]
Ah... my mistake. It took the old installed version. I can see this now:
```
root@a036296c9ed8:/work# ./run-test
INFO:  # ./tests/testpage.png
INFO:  === ./tests/testpage.png 1
INFO:  estimating skew angle
INFO:  estimating thresholds
INFO:  rescaling
^CTraceback (most recent call last):
  File "/usr/local/bin/ocropus-nlbin", line 211, in <module>
    process1((f,i+1))
  File "/usr/local/bin/ocropus-nlbin", line 184, in process1
    flat -= lo
root@a036296c9ed8:/work# ./run-rtrain
++ dirname ./run-rtrain
+ BASE=.
+ tar -zxf ./tests/uw3-500.tgz
+ ./ocropus-rtrain 'book/*/*.bin.png' -o uw3-500-model
# inputs 500
# tests None
# CenterNormalizer
# using default codec
# charset size 157 [ ~!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWX
[\]^_`abcdefghijklmnopqrstuvwxyz{|}]
# last_trial 0
Traceback (most recent call last):
  File "./ocropus-rtrain", line 289, in <module>
    pcs = network.trainSequence(line,cs,update=do_update,key=fname)
  File "/work/ocrolib/lstm.py", line 903, in trainSequence
    self.aligned = array(ctc_align_targets(self.outputs,self.targets,debug=sel
debug_align))
  File "/work/ocrolib/lstm.py", line 812, in ctc_align_targets
    outputs = outputs * 1.0/sum(outputs,axis=1)[:,newaxis]
TypeError: sum() takes no keyword arguments
```

**Comment by zuphilip** [comment]
Okay, I hope that https://github.com/tmbdev/ocropy/pull/179/commits/2222227c76060b2f76188780fbb57168eb6efef2 will fix this. Can some confirm that? Then I will merge the PR.

**Comment by QuLogic** [comment]
That's why it's best not to use *-imports. Really should replace those with `np.<func>` instead of shadowing builtins.

**Comment by lunactic** [comment]
I will test it tomorrow morning and come back with results

**Comment by zuphilip** [comment]
@QuLogic Yes, we created an issue for that #176 which also links to your commits. This seems to be a good idea and I hope we find time to continue working on this.

**Comment by lunactic** [comment]
2222227 seems to fix it for me.

Thanks for the quick fix!
