### ISSUE TITLE
ValueError: shape mismatch in `ocropus-gpageseg`

### ISSUE THREAD

**Issue by danvk** [tmbdev/ocropy#18]
When I run `ocropus-gpageseg` on the following image:

![0001 bin](https://cloud.githubusercontent.com/assets/98301/5667041/8c1deeda-9732-11e4-8ef3-a06b12118686.png)

I get a `ValueError` which prevents any lines from being extracted:

```
$ ocropus-gpageseg -n --minscale 10 --maxcolseps 0 book-703662b.crop/0001.bin.png

########## /usr/local/bin/ocropus-gpageseg -n --minscale 10 --maxcolsep

book-703662b.crop/0001.bin.png
scale 13.8564064606
computing segmentation
computing column separators
computing lines
propagating labels
spreading labels
number of lines 4
finding reading order
writing lines
1: (slice(3L, 32L, None), slice(3L, 607L, None))
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-gpageseg", line 435, in safe_process1
    process1(job)
  File "/usr/local/bin/ocropus-gpageseg", line 408, in process1
    binline = psegutils.extract_masked(1-cleaned,l,pad=args.pad,expand=args.expand)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/toplevel.py", line 213, in argument_checks
    result = f(*args,**kw)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/psegutils.py", line 114, in extract_masked
    line = where(mask,line,amax(line))
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Comment by tmbdev** [comment]
I believe ocropus-gpageseg isn't supposed to be run on the .bin.png file, but on the original .png file; it will look for the .bin.png file on its own.

(It should still work on pure binary PNG images anyway, so I'll look at that. Or maybe you could see whether you can come up with a patch.)

**Comment by danvk** [comment]
The [README](https://github.com/tmbdev/ocropy/blob/master/README.md) indicates that it should be:

    # perform binarization
    ./ocropus-nlbin tests/ersch.png -o book

    # perform page layout analysis
    ./ocropus-gpageseg 'book/????.bin.png'

Does it need to be updated? I'll see if I can figure out what's going on, too.

**Comment by tmbdev** [comment]
Did you generate the .bin.png files in some other way than with ocropus-nlbin?

PNG files come in two varieties: binary and full color; both can contain binary images, however. They turn into rank 2 or rank 3 arrays inside Python, and some image processing operations only work on one or the other, some work on both.

**Comment by adnanulhasan** [comment]
ocropus-gpageseg works on binarized images, that is on .bin.png. You may need to look how your binarized images were generated. Run ocropus-nlbin to confirm for few images.

**Comment by danvk** [comment]
That image is generated by `ocropus-nlbin`. Here's the original:

![703662b crop](https://cloud.githubusercontent.com/assets/98301/5670965/a24a7596-9752-11e4-8cf3-94b33bd6443c.png)

and my sequence of commands:

```
$ ocropus-nlbin -n 703662b.crop.png -o /tmp/book
# 703662b.crop.png
=== 703662b.crop.png 1
flattening
/usr/local/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:532: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
estimating skew angle
estimating thresholds
rescaling
703662b.crop.png lo-hi (0.60 0.95) angle  0.0
writing

$ ocropus-gpageseg -n --minscale 10 --maxcolseps 0 /tmp/book/0001.bin.png

########## /usr/local/bin/ocropus-gpageseg -n --minscale 10 --maxcolsep

/tmp/book/0001.bin.png
scale 13.8564064606
computing segmentation
computing column separators
computing lines
propagating labels
spreading labels
number of lines 4
finding reading order
writing lines
1: (slice(3L, 32L, None), slice(3L, 607L, None))
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-gpageseg", line 435, in safe_process1
    process1(job)
  File "/usr/local/bin/ocropus-gpageseg", line 408, in process1
    binline = psegutils.extract_masked(1-cleaned,l,pad=args.pad,expand=args.expand)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/toplevel.py", line 213, in argument_checks
    result = f(*args,**kw)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/psegutils.py", line 114, in extract_masked
    line = where(mask,line,amax(line))
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Comment by danvk** [comment]
I believe the issue is that the detected lines are too close to the edge of the image. Adding ~10px of padding to all sides of the binarized image makes the error go away.
