### ISSUE TITLE
Delete some parameters in ocropus-gpageseg

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/ocropy#183]
By looking a little closer to [`ocropus-gpageseg`](https://github.com/tmbdev/ocropy/blob/master/ocropus-gpageseg) and [starting to write the purpose of some parameters up](https://github.com/tmbdev/ocropy/wiki/Page-Segmentation), it seems that some parameter are deprecated, not used any more, or could otherwise be deleted. To avoid any unknown depencies on these parameter, we can discuss these first here in this issue:

1. The `--zoom`-parameter was never used in the page segmentation, but it is only used in the binarization and some older scripts. Actually, it looks for me, that maybe this parameter was copy (together with its description) a long time ago from an old script and never looked at in detail since then. ==> Can we delete the `--zoom` completely from `ocropus-gpageseg`? https://github.com/tmbdev/ocropy/pull/181
1. PR https://github.com/tmbdev/ocropy/pull/172 corrected the behavior for `--maxcolseps 0` resp. `--maxseps 0` which is now equal to not taking any white space separators resp. no black separators (previously this was, rather by mistake, equal to be unbounded). Thus, we can deactivate completely the white space resp. black separators by this parameter and there is actually no need for a special parameter `-b`. ==> Should we delete the option `-b` completely and rather switch to the default value `0` for `--maxseps`?
1. The option `--csminaspect` is used in the function `compute_colseps_morph` which is not used any more. It is rather the function `compute_colseps_conv` used. ==> Is there any reason to keep the parameter `--csminaspect`?

**Comment by mittagessen** [comment]
If it helps I've done exactly the same in kraken. In fact I've removed all parameters except scale, maximum number of columns and the selectors for black and white separators, as there were basically no use cases for adjusting these. Black and white separators are still handled separately.

For reasons of backwards compatibility it is probably reasonable to keep these parameters but document them as ignored. That seems to be the standard for other tools carrying around a lot of legacy parameters, such as gnupg. That's also necessary as the CLI is the only callable interface from third party software making "API" changes undesirable.

**Comment by zuphilip** [comment]
Yes, this is helpful. Also the suggestion to keep some deprecated parameters and just document their status for backwards compatibility sounds like a good solution for 2. and 3. Thank you very much @mittagessen !

**Comment by zuphilip** [comment]
See https://github.com/tmbdev/ocropy/pull/181/commits/ac9659d717f1d6463851618bec4167c98c5d798f for suppressing a parameter from the help, continued in #181 .

**Comment by zuphilip** [comment]
Closed by cd81476.
