### ISSUE TITLE
Old code for skew estimation

### ISSUE THREAD

**Issue by ChillarAnand** [tmbdev/ocropy#187]
In OLD code, there was a [module named ocrorast](https://github.com/tmbdev/ocropy/blob/97ace5581b4c4deb95cfcd17b595b0ff1da36c25/OLD/ocrotest-smartpre#L26). 

It is not present in the latest version. Grepping through deleted files also didn't help. 

    git log --diff-filter=D --summary | grep delete | grep ocrorast

Can you help in locating that module?

**Comment by zuphilip** [comment]
This looks for me as it come from the old C++ version with different subdirectories. See here https://github.com/tmbdev/ocropy/wiki/Older-versions and https://github.com/tmbdev/ocropy/issues/61 for general info about old versions.

The only reference I found now for ocrorast is here https://searchcode.com/file/2389564/ocrorast/ocrorast.h

**Comment by amitdo** [comment]
>In the old days there was a main 'ocropus' repository with references to 'ocropy' and other sub-repos. The versions were attached to the main repository.

One of the other repos was `ocrorast`. RAST` was the name of the layout analysis algorithm. 

The code was 'forked' from the 0.4.x monolithic `ocropus` repo
https://github.com/michaelyin/ocropus-git/tree/master/ocr-layout

In the `ocrorast` repo there was a python binding to the C++ code.

**Comment by ChillarAnand** [comment]
@zuphilip @amitdo Thanks for the help.

**Comment by amitdo** [comment]
>The only reference I found now for ocrorast is here https://searchcode.com/file/2389564/ocrorast/ocrorast.h

Click 'View File Tree' to see all files.

Here is the Python binding (SWIG):
https://searchcode.com/file/2389565/ocrorast/ocrorast.i

**Comment by amitdo** [comment]
Maybe someone wants to create a script that will copy all the tree and upload it to GitHub.

**Comment by amitdo** [comment]
Or just ask Tom if he can upload all the sub-repos (if he kept them somewhere).

**Comment by zuphilip** [comment]
> Maybe someone wants to create a script that will copy all the tree and upload it to GitHub.

We will look into this. CC @stweil

**Comment by amitdo** [comment]
Leptonica, an image processing library (used by Tesseract), also has code for page skew finding:
https://github.com/DanBloomberg/leptonica/blob/master/src/skew.c
https://github.com/DanBloomberg/leptonica/blob/master/prog/skewtest.c

**Comment by zuphilip** [comment]
I have copied the code from searchcode here https://github.com/zuphilip/ocropus-from-searchcode
