### ISSUE TITLE
Can anyone have any links of materials which explain the architecture  of this code.

### ISSUE THREAD

**Issue by deepu01234** [tmbdev/ocropy#211]
Can anyone have any links of materials which explain the architecture of this code.

**Comment by zuphilip** [comment]
Start here: https://github.com/tmbdev/ocropy/wiki

**Comment by deepu01234** [comment]
Thanks zuphilip :).
I am trying to build a OCR tool and i pass the our data through this.The accuracy is very low.can you please suggest me what are the different enhancement/modifications we need to do here to achieve the good accuracy?

**Comment by zuphilip** [comment]
Example image, call and output?

**Comment by deepu01234** [comment]
Hi Zaphilip -
please see the example image - [https://drive.google.com/file/d/0B9s_cXxj3yG-WmhZLVBqdnlSQms/view?usp=sharing]

after getting the html output i am calculating the WER (word error rate) using ground truth data but the accuracy is very low so i found out there is two things two achieve the better accuracy -
1) training of LSTM network on the my own data set.
2)using the image preprocessing. for image preprocessing i gone through the code and found there is two file where the preprocessing is happening   a-ocropus-nlbin, b- ocropus-gpageseg ,so bacially two filters aare there Gaussian and  morphological  operations so can you please tell me if i can modify there pre-processing techniques for our data set can we achieve the better accuracy? and which file i have to modify for the image preprocessing ?.

Please guide me.
Thanks.

**Comment by zuphilip** [comment]
You need to scan your documents with 300 dpi to achieve better OCR quality. The current image has too low resolution, e.g

<img width="400%" src="https://cloud.githubusercontent.com/assets/5199995/25780622/9fb58cfa-332a-11e7-8e75-5af78381f872.png"/>

<img width="400%" src="https://cloud.githubusercontent.com/assets/5199995/25780631/f21ad91e-332a-11e7-93df-8e0aecdf40ce.png"/>

**Comment by deepu01234** [comment]
Sorry to mention that before feeding into this tool i am converting this into 300 dpi i have attached the original image.
for e.g- https://drive.google.com/open?id=0B9s_cXxj3yG-WnU2enF3OFBzTUk

Still accuracy is low.
Also i have added some questions related to the image preproceesing  can you please help me?

**Comment by zuphilip** [comment]
The picture still only has 626 x 885 pixels which looks like a scanned A4 paper with 75 dpi. You should increase the quality during scanning, i.e. scan this A4 paper with 300 dpi which would then result in about 2504 x 3540 pixels. (Any converting afterwards should at also resize/resample the picture.)

**Comment by deepu01234** [comment]
i have checked this it is 300 dpi and dimensions is 1240*1754.

**Comment by deepu01234** [comment]
Hi zuphilip,
can you please help me in the image preocessing in this module? I wanted to modify some of the filters like gaussian_filter etc. but i don't know where i can modify these filters i gone through the  **ocropus-nlbin** file and modified some of the parameter but nothing is affected.
Can you please tell me which is the best way to enhance the image preprocessing module of this tool?.

**Comment by zuphilip** [comment]
If you change some code files, then you either have to call the scripts directly with `./ocropus-nlbin` or run `python setup.py install` again.

**Comment by xiaomaxiao** [comment]
search  "The OCRopus Open Source OCR System"  may be usefull for you . 

you can seach author "Faisal Shafait" ， you will find many papers about OCRopus.

I am also  trying to build a OCR tool , but i am not understan the code , because too little comments or links about the algorithm

**Comment by amitdo** [comment]
>search "The OCRopus Open Source OCR System" may be usefull for you .

The paper 'The OCRopus Open Source OCR System' is from 2008. It's totally irrelevant to understanding the current codebase.

Look here:
https://github.com/tmbdev/ocropy/wiki/Publications

**Comment by xiaomaxiao** [comment]
@amitdo  any about  papers of page frame detection ?

**Comment by amitdo** [comment]
>any about papers of page frame detection ?

Not sure what you are asking here:
1) Does any of the papers in the Publications page has details about page frame detection?
2) Do you know any paper about page frame detection?
3) Do you know any paper written by ocropus' authors about page frame detection?

My answers:
For option 1 - No, AFAIK
For option 2 - I don't have links for you. You'll need to search by yourself.
For option 3 - I don't know if they wrote about this subject.

**Comment by amitdo** [comment]
This paper is mention in  'The OCRopus Open Source OCR System'.
https://pdfs.semanticscholar.org/62b8/01c2c6c48a9e7b587315cdb24f4b708cc8b0.pdf

Here is an old version of ocropus:
https://github.com/zuphilip/ocropus-from-searchcode

https://github.com/zuphilip/ocropus-from-searchcode/search?q=frame

**Comment by xiaomaxiao** [comment]
@amitdo  , i am sorry for  my poor English.

I just found in OCRopus , and not found in ocropy/ocropus-gpageseg , 

if this method is not working ? so ocropy give up it.

**Comment by amitdo** [comment]
Sorry, but I do not understand you :-(

**Comment by xiaomaxiao** [comment]
@amitdo this paper about page frame detection   https://pdfs.semanticscholar.org/62b8/01c2c6c48a9e7b587315cdb24f4b708cc8b0.pdf

just found in OCRopus , and not found in ocropy/ocropus-gpageseg.

Is there a better method in ocropy?

**Comment by amitdo** [comment]
Now I understand :-)

I believe that there is no such method in the current version of ocropy.
