### ISSUE TITLE
OUT training empty

### ISSUE THREAD

**Issue by maiconramones** [tmbdev/ocropy#221]
I tried to train ocropus with synthetic data and with html corrections. 

In both case the OUT always is empty with ' ' varying the length.

What I doing wrong?

## Your Environment
* Python version: Python 2.7.12
* Git revision of ocropy: e3080d247d4251375329f3fa21438929fee09b42
* Operating System and version: Ubuntu 16.04.2 LTS

**Comment by zuphilip** [comment]
Does the `./run-rtrain` work for you as expected? Typically the first ~100 steps will lead to empty output, but then it should start to recognize spaces and after ~250 steps also some characters (e.g. `e`, `a`, `n`) and so on.

**Comment by maiconramones** [comment]
Thanks for the quick reply @zuphilip  I tried with this: ./ocropus-rtrain -o firstModel linegen/*/*.bin.png

**Comment by zuphilip** [comment]
Please try first
```
./run-rtrain
```
to see whether training with the test data (images and ground truth data) is working. Afterwards, we can continue to look at your data.

**Comment by maiconramones** [comment]
Ok @zuphilip I started ./run-rtrain now it's necessary to wait some hours. There are some parameter to improve this process? Because it's too slow.

I started my rtrain 3 hours ago and it still running... but now my output is the same for TRU ALN and OUT:
3239 3.29 (2251, 48) linegen/Courier Prime/010122.bin.png
   TRU: u'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z'
   ALN: u'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z'
   OUT: u'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z'

I provided a simple synthetic data with the caracters. It's correct?

**Comment by zuphilip** [comment]
This seems that you learned this one line perfectly. So far so good. In general you want to learn a lot of different lines. And training can take some time.

**Comment by maiconramones** [comment]
Good news! My rtrain still running but the ./run-train no.  Stopped with the stack below.

What's the best way to train? Because I generated a simple tree lines with linegen. 

---Stack
# oops, got FloatingPointError overflow encountered in exp
Traceback (most recent call last):
  File "./ocropus-rtrain", line 296, in <module>
    network = load_lstm(last_save)
  File "./ocropus-rtrain", line 182, in load_lstm
    network = ocrolib.load_object(last_save)
  File "/home/ubuntu/ocropy/source/ocrolib/common.py", line 436, in load_object
    fname = ocropus_find_file(fname)
  File "/home/ubuntu/ocropy/source/ocrolib/common.py", line 639, in ocropus_find_file
    full = os.path.join(prefix, basename, fname)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by maiconramones** [comment]
Hy,

Something is very wrong on my setup or I made serious mistake about the training process. My training generate 41 pyrnn.gz files but the recognition doesn't work on the contrary was worse than the english recognize.
 
In some case the pyrnn.gz generate this output 
  File "./ocropus-rpred", line 264, in safe_process1
    return process1(arg)
  File "./ocropus-rpred", line 220, in process1
    ocrolib.write_text(base+".txt",pred)
  File "/home/ubuntu/ocropy/source/ocrolib/common.py", line 107, in write_text
    if not nonl and text[-1]!='\n':
IndexError: string index out of range
