### ISSUE TITLE
adding more telugu characters to chars.py 

### ISSUE THREAD

**Issue by harinath141** [tmbdev/ocropy#223]
Hi
I have seen chars.py in ocrlib directory. In telugu we need to add more characters like 
'్శ'ై్ '్జ'్ఝ'్న'ి''ీ''్భ'ే '్త'్మ్  ్ఛ ్ర ం'్ఞ ె ్ఠ ్ద ్ఙ ్స ్ఱ ్ఢ ్ధ ్ఖ ్ల '్య ్' '్థ ౄ '్ష ్హ ్ప'్ట ్ళ'్ఫ ్ణ '్క ్బ ్ఘ ్వ ్డ ్భ ్ఫ ి  '్  ్చ ్మ ్ఖ ్పు ్న ్వ ్త
here ' symbol can be removed but i cant able to remove space in between the characters... if we remove the characters will merge.. so is it ok? if we put space in between the characters... if so kindly add these to chars file...

**Comment by zuphilip** [comment]
I am afraid that I don't know Telugu characters or its encoding. Maybe @ChillarAnand can help here?

**Comment by harinath141** [comment]
@zuphilip thanks for your response,
Can I add this characters with spaces? Can the system trim spaces while processing if I add this characters..?

**Comment by ChillarAnand** [comment]
I guess spaces are related to rendering issues and we dont need to worry about it.

As @zuphilip  mentioned here, you can add [characters to a file](https://github.com/tmbdev/ocropy/issues/162#issuecomment-269759804) and pass it ocropy with `-c c.txt`.

**Comment by zuphilip** [comment]
For Telugu the characters are added to chars.py in 38addd313ad815d2435c0ccf5ec900dcaa0c55a4, but they are not part of the default set. The usage can be done with a separate file.
