### ISSUE TITLE
Question: What is the procedure for using Ocropy with non alpha numeric characters

### ISSUE THREAD

**Issue by urhub** [tmbdev/ocropy#224]
I have text that use unicode characters, in addition to alpha numeric characters. 
I searched through the issues and found that I can train using the -c option.
The training output shows that the output of the RNN is correct,
119004 0.18 (530, 48) 010010.bin.png
   TRU: u'12. Hi\u02bbo\u02ca kini akua o Ka-hiki;'
   ALN: u'12. Hi\u02bbo\u02ca kini akua o Ka-hiki;'
   OUT: u'12. Hi\u02bbo\u02ca kini akua o Ka-hiki;'
However the recognition step, ocropus-rpred, the output is all wrong. 
The unicode characters are not being recognized or synthesized.
What is the correct procedure to handle non alpha numeric characters?

**Comment by zuphilip** [comment]
Usually, also the recognition of non-ASCII characters should just work without anything additionally. For example some special characters in German like `äöü` or French `éèô` are already in the standard character set, and this works fine. There is also models for Cyrillic, Asian or Indic scripts https://github.com/tmbdev/ocropy/wiki/Models .

>  I can train using the -c option.

What is your exact call here for training? Which language/scripts are you trying to train?

> ocropus-rpred, the output is all wrong.

What is the output then compared to the expected output? Did you check that this is not only a problem with showing these characters on the command line?

**Comment by urhub** [comment]
Sorry, I forgot to mention that I am starting with the default model. If I start from scratch there are no issues. The language is English, but it is used to represent Hawaiian sounds, hence the unicode characters. I worked on this during the summer and made some progress. I found that editing the file chars.py and including the additional unicode characters almost achieves the objective.

**Comment by zuphilip** [comment]
The recognized characters `›‹€†ÿâö` are part of the default character set (`ö` is from German, `â` and `ÿ` from French, etc.). Thus, it looks that the recognition ignores your characters completely. How do you call the recognition exactly?

**Comment by urhub** [comment]
Here is the command, results are the same with and without the environment variable:
env PYTHONIOENCODING=UTF-8 ocropus-rpred -n temp/????/??????.bin.png -m ./models/mele_unicode_over_default/mele-unicode-mod-00109000.pyrnn.gz

**Comment by zuphilip** [comment]
Rereading:

> Sorry, I forgot to mention that I am starting with the default model. If I start from scratch there are no issues.

Ah, I think it is not possible to change the character set when using an existing model. See also https://github.com/tmbdev/ocropy/issues/227#issuecomment-309379767

**Comment by urhub** [comment]
Got it. Thanks, Phillip.
