### ISSUE TITLE
Auto load recent model while training?

### ISSUE THREAD

**Issue by ChillarAnand** [tmbdev/ocropy#231]
## Expected Behavior
If training is stopped and started it should auto pick latest saved model.

## Current Behavior
Users have to manually provide the previous model.

## Possible Solution
When setting output `-o`, provide only base name. ocropy keeps saving model after N iterations. When training is stopped and restarted, pick the latest saved model.

**Comment by zuphilip** [comment]
I am not convinced that we should add this such a feature. The only thing which you could save would be the 8-digit number, which should be quite easy to find the latest one by using autocomplete (pressing `tab`). Alternatively, you could write a custom bash script for that.
