### ISSUE TITLE
Improve code styling

### ISSUE THREAD

**Issue by ChillarAnand** [tmbdev/ocropy#232]
![c](https://user-images.githubusercontent.com/4463796/28243964-fa71149c-69f9-11e7-81d6-e7293408fbb5.png)

It is hard to read code in editors as it is not formatted correctly. We can use tools like autopep8, yapf to automatically fix those issues.

Also, add flake8 to Travis.

**Comment by zuphilip** [comment]
PEP8 coding style sounds generally good for me. But I think this would involve in a huge amount of changes through all files. Some time ago I started to add more unit tests to increase also coverage and I would feel more save when we have them in place, before improving coding style.

@tmbdev, @kba, @QuLogic, @amitdo, what do you think about PEP8 coding style?

**Comment by christophered** [comment]
@mittagessen @theraysmith @tmbdev 
News:
tmbdev; the developer of CLSTM and Ocropy, [is planing to release a new software with GPU capabilities, better layout analysis and much more.](https://github.com/tmbdev/ocropy/commit/7eac431df3b4fa533e35e23540624cce8b0e8549)
I spoke with him as he stated that, quote: `It's language independent` & `You can probably run it on Windows. All it requires is Python and CUDA`
I'm hyped!

![ocropy007](https://user-images.githubusercontent.com/16248376/28947877-f1865caa-78ba-11e7-84a9-2c2c10bd77b7.jpg)

**Comment by zuphilip** [comment]
@christophered Yes, it is interesting news. But this issue here is about coding style. Please consider another place to post this, maybe the [Gitter chat](https://gitter.im/tmbdev/ocropy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) would be appropriate? We should delete this post from here.

**Comment by zuphilip** [comment]
Some of the issues about the coding style should be improved. If you encounter anything specific which should be urgently improved then just let us know, or create a PR. Closing this issue now.
