### ISSUE TITLE
can't download en-default.pyrnn.gz

### ISSUE THREAD

**Issue by jwilk** [tmbdev/ocropy#24]
$ wget -nd http://www.tmbdev.net/en-default.pyrnn.gz
    --2015-01-09 20:06:04--  http://www.tmbdev.net/en-default.pyrnn.gz
    Resolving www.tmbdev.net (www.tmbdev.net)... 69.163.203.33
    Connecting to www.tmbdev.net (www.tmbdev.net)|69.163.203.33|:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2015-01-09 20:06:05 ERROR 404: Not Found.

**Comment by adnanulhasan** [comment]
There is now a new directory called 'ocropy-old' from where you can download the default model. so just issue
$ wget -nd http://www.tmbdev.net/ocropy-old/en-default.pyrnn.gz

**Comment by tmbdev** [comment]
Sorry, I'm just cleaning up the directory tree. I put the default model back in its original place.

**Comment by jplethier** [comment]
It is again impossible to download the en-default.pyrnn.gz, because the www.tmbdev.net is out
