### ISSUE TITLE
ocropus-gpageseg   ERROR  less than --minscale

### ISSUE THREAD

**Issue by wanghaisheng** [tmbdev/ocropy#241]
```
docker@93498577c7b6:~/pic$  ocropus-gpageseg  --csminheight 100000 --usegauss -n   a90c158fjw1ekmiqfxt4fj20dc0hsdif.nrm.png
INFO:  
INFO:  ########## /usr/local/bin/ocropus-gpageseg --csminheight 100000 --usega
INFO:  
INFO:  a90c158fjw1ekmiqfxt4fj20dc0hsdif.nrm.png
INFO:  scale 8.485281
ERROR:  a90c158fjw1ekmiqfxt4fj20dc0hsdif.nrm.png: scale (8.48528) less than --minscale; skipping
```
when explictly set minscale ,it still
```
docker@93498577c7b6:~/pic$  ocropus-gpageseg  --csminheight 100000 --usegauss -n   a90c158fjw1ekmiqfxt4fj20dc0hsdif.bin.png --minscale 5.0
INFO:  
INFO:  ########## /usr/local/bin/ocropus-gpageseg --csminheight 100000 --usega
INFO:  
INFO:  a90c158fjw1ekmiqfxt4fj20dc0hsdif.bin.png
INFO:  scale 8.485281
INFO:  computing segmentation
INFO:  computing column separators
INFO:  considering at most 3 whitespace column separators
INFO:  computing lines
INFO:  propagating labels
INFO:  spreading labels
INFO:  number of lines 56
INFO:  finding reading order
INFO:  writing lines
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-gpageseg", line 443, in safe_process1
    process1(job)
  File "/usr/local/bin/ocropus-gpageseg", line 425, in process1
    ocrolib.write_page_segmentation("%s.pseg.png"%outputdir,segmentation)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/toplevel.py", line 213, in argument_checks
    raise e
CheckWarning: 
CheckWarning for argument image of function <function write_page_segmentation at 0x7fa58b611410>
<ndarray-7fa58b5c22b0 (640, 480) int32 [0,65586]> of type <type 'numpy.ndarray'>: expect a page image (larger than 600x600)(This can happen occasionally during normal operations and isn't necessarily a bug or problem.)


```
![a90c158fjw1ekmiqfxt4fj20dc0hsdif nrm](https://user-images.githubusercontent.com/2363295/30374584-1137873c-98b8-11e7-9963-da3f15cae5b9.png)

**Comment by Sultan91** [comment]
Same problem

**Comment by Sultan91** [comment]
You can re-set values fed as arguments by adding this code to ocropus-gpageseg file
`class Namespace:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

args = Namespace(
    blackseps=False,
    csminaspect=1.1,
    csminheight=10, 
    debug=False, 
    expand=3, 
    files=[], 
    gray=True, 
    hscale=1.0, 
    maxcolseps=3, 
    maxlines=300, 
    maxseps=0, 
    minscale=8.3, 
    nocheck=True, 
    noise=8, 
    pad=3, 
    parallel=0, 
    quiet=False, 
    scale=0.0, 
    sepwiden=10, 
    threshold=0.2, 
    usegauss=False, 
    vscale=1.0)`

**Comment by zuphilip** [comment]
@wanghaisheng The second error `... expect a page image (larger than 600x600)` should be fixed after merging #220. Please update to the newest version and try it again.

**Comment by Crescentz** [comment]
same question

**Comment by zuphilip** [comment]
If you mean that you have a "less than --minscale" ERROR, then you can add the parameter `--minscale 5.0` (or another suitable value for your case).
