### ISSUE TITLE
ocropus-rpred does not accept a custom codec

### ISSUE THREAD

**Issue by lorenzob** [tmbdev/ocropy#242]
I trained a model using the --codec option of ocropus-rtrain and during training everything works fine.

But when I use the generated model with ocropus-rpred I obtain "remapped" characters instead of the correct answer.

My quick fix was this:

```py
parser.add_argument("--codec",default=[],nargs='*',
                    help="construct a codec from the input text")

[...]

# This is just cut-paste from ocropus-rtrain
if args.codec!=[]:
    print("# building codec")
    codec = lstm.Codec()
    charset = set()
    print(args.codec)
    for fname in ocrolib.glob_all(args.codec):
        transcript = ocrolib.read_text(fname)
        l = list(lstm.normalize_nfkc(transcript))
        charset = charset.union(l)
    charset = sorted(list(charset))
    charset = [c for c in charset if c>" " and c!="~"]
else:
    print("# using default codec")
    charset = sorted(list(set(list(lstm.ascii_labels) + list(ocrolib.chars.default))))

charset = [""," ","~",]+[c for c in charset if c not in [" ","~"]]
print("# charset size", len(charset), end=' ')
if len(charset)<200:
    print("[" + "".join(charset) + "]")
else:
    s = "".join(charset)
    print("[" + s[:20], "...", s[-20:] + "]")
codec = lstm.Codec().init(charset)

[...]

# After the network is fully loaded
network.codec = codec
```

and it works fine. I think something like this should be added to rpred.

BTW I do not understand why "~" is a mandatory character in the codec.

**Comment by zuphilip** [comment]
If you use a custom model for the prediction, then the codec will be read from that model automatically.

> But when I use the generated model with ocropus-rpred I obtain "remapped" characters instead of the correct answer.

I don't understand what you mean with "remapped" characters. Can you give an example?

There are some automatic replacements hard coded in `chars.py`, like replacing the ligature `ﬄ` with `ffl`, see https://github.com/tmbdev/ocropy/blob/master/ocrolib/chars.py#L37-L59 . If you don't want these normalization steps then you can use `--nonormalize` in the prediction step.

**Comment by lorenzob** [comment]
I train the model with an image representing the word "PIZZA". During the training, I can see "PIZZA" as the recognized text.
Later, when I run the model for prediction, the output is (random example) "DUWWK". The mapping is like:

P -> D, I -> U, Z -> W, K -> A 

and this is the same for all the samples (I suspect the characters are just shifted, not shuffled as in this example). Providing a custom codec with the above code fixes this.
This is the codec I'm using

0123456789
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
'(),-./
<empty line>

(split on three lines, plus an empty line at the end. I'm noticing this right now, I do not if it's relevant or not).

In the meantime I moved to clstm so I can no longer easily test this.

**Comment by zuphilip** [comment]
Thank you. I have never heard anything similar. Maybe, it is related to the empty lines in your custom codes.

> In the meantime I moved to clstm so I can no longer easily test this.

Okay, then I suggest that we close this issue.

**Comment by rogerfitz** [comment]
Bump. Experiencing this too. My charset is 
`charset size 72 [ ~%'()*,-./0123456789:<?ACDEFGHILMNOPRSTUVabcdefghijklmnopqrstuvwxyz°•⁄]`
and example output is generating "EMZ^QVO EQbM +). \MI[XWWV~*(1 O$"
I'm confused because some of those chars generated aren't in my original charset
