### ISSUE TITLE
ocorpus-rpred failure, when empty text is recognized

### ISSUE THREAD

**Issue by rnsrk** [tmbdev/ocropy#243]
I use two scripts to compute the error rates of my models (lend from https://github.com/jze):

ocropus-model-precision.sh:                             
```
#!/bin/sh                                                                       

# Create a plot of the model precision during the training of a model.          
# You get a graph showing the error rate for training and testing data to       
# check if you ran into overfitting.                                            

echo "Stufe;Testdata;Traindata" > errors.csv

for m in models/*.pyrnn.gz; do
        echo $m
        n=`echo "$m" | sed 's/^.*-0//' | sed 's/.pyrnn.gz//'`
        p1=`./ocropus-precision.sh $m testing |tail -n1`
        p2=`./ocropus-precision.sh $m training |tail -n1`
        echo "${n};${p1};${p2}"  >> errors.csv
done
```

and ocropus-precision.sh

```
#!/bin/sh
MODEL=$1
DIR=$2

if [ ! -e "$MODEL" ]; then
	echo "USAGE: ocropus-genauigkeit.sh <MODEL-FILE>"
	exit 1
fi

if [ ! -n "$DIR" ]; then
	DIR=testing
fi

if [ ! -d $DIR ]; then
	echo "Missing directory 'testing' that contains the image and ground truth for test."
	exit 1
fi

TEMP=`mktemp -d`

cp $DIR/*.png $TEMP
cp $DIR/*.gt.txt $TEMP

ocropus-rpred -q -Q 8 -m $MODEL $TEMP/*.png
ocropus-econf $TEMP/*.gt.txt 
ocropus-errs -e $TEMP/*.gt.txt 

# Create a correction.html file that contains lines with differences. This file can be used to spot typos in the ground truth.
#WITHDIFF=`ocropus-errs $TEMP/*.gt.txt 2>/dev/null |grep -v "^     0" | cut -b 15- | sed 's/.gt.txt/.png/' `
#ocropus-gtedit html $WITHDIFF

rm -fr $TEMP
```

## Expected Behavior
It should just create a file errors.csv with the error rates of the models from testing and training folders. 

## Current Behavior
The script does create the errors.csv, as expected, but ocropus-rpred gives constantly that failure:

> rn@rn-uni:~/work/ocr/trainingsdata/zedler$ sh ocropus-model-precision.sh 
> models/book-00001000.pyrnn.gz
> Traceback (most recent call last):
>   File "/usr/local/bin/ocropus-rpred", line 264, in safe_process1
>     return process1(arg)
>   File "/usr/local/bin/ocropus-rpred", line 220, in process1
>     ocrolib.write_text(base+".txt",pred)
>   File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 107, in write_text
>     if not nonl and text[-1]!='\n':
> IndexError: string index out of range

## Possible Solution
I have some special characters in my codec, like ū, m̄, n̄ or ½ ¾, maybe they lead to confusions.

## Your Environment

* Python version: Python 2.7.13

* Git revision of ocropy: 
downloaded 01.01.2017
* Operating System and version:
Ubuntu 17.04 x64

**Comment by zuphilip** [comment]
The error
> File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 107, in write_text
if not nonl and text[-1]!='\n':
IndexError: string index out of range

indicates that the `text` is empty  for this example in l[ine 107 of common.py](https://github.com/tmbdev/ocropy/blob/ae84a8edaf0b76135f749ba66fc30c272d0726d0/ocrolib/common.py#L107). Which line was looked at in the `ocropus-rpred` call before this error? I guess this is [logged in the output message](https://github.com/tmbdev/ocropy/blob/master/ocropus-rpred#L219) immediately before the error. Can you share exactly this text (image) line here?

**Comment by rnsrk** [comment]
You are right, the error appears with files _recognised_ empty, the corresponding images have always very few characters, like
![zedler_0005_010004 bin](https://user-images.githubusercontent.com/29227376/30740611-fff08bdc-9f91-11e7-9345-10f3d0571a5c.png)
or
![zedler_0008_010009 bin](https://user-images.githubusercontent.com/29227376/30740637-1a990e64-9f92-11e7-9cf2-6c982e58840e.png)
that explains, why the error appears only from time to time, because with a better model, the line is recognised. Maybe it is better to sort this kind of images out.

**Comment by zuphilip** [comment]
Okay, I see this depends also on the model. But if empty text is the trigger, then we should also handle that case in the code correctly. I will reopen the issue here, because I want to fix that boundary case.

**Comment by kba** [comment]
https://github.com/tmbdev/ocropy/commit/f9b50fbf555334ceda50b26eaace72a07d3bfeaf should fix this, but would be good to test it.
