### ISSUE TITLE
lstm.py RuntimeWarning: overflow encountered 

### ISSUE THREAD

**Issue by rnsrk** [tmbdev/ocropy#246]
While using ocropus.rpred, the error /usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py:383: RuntimeWarning: overflow encountered in exp return 1.0/(1.0+exp(-x)) appears.

## Current Behavior
Errors appears while error computing process described in https://github.com/tmbdev/ocropy/issues/243
The lines are recognised and saved as expected, but randomly the error above occurs, looks like:

> 
> INFO:  training/zedler_0013_01002c.bin.png:9. Bernardinus gidius Recchi, An. 1711.
> INFO:  training/zedler_0013_01002e.bin.png:Aquapendente (Hieronjmus Fabricius ab) siehe
> INFO:  training/zedler_0013_010030.bin.png:Aquapendente (Micolaut ab) ein Jtaliäner, aus
> /usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py:383: RuntimeWarning: overflow encountered in exp
>   return 1.0/(1.0+exp(-x))
> INFO:  training/zedler_0013_010031.bin.png:dem Orden S. Augustini, schrieb de Raptiso: a Pec-
> INFO:  training/zedler_0013_010032.bin.png:e o trigiu ali: de Pr tenti : de s, infero,
> /usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py:383: RuntimeWarning: overflow encountered in exp
>   return 1.0/(1.0+exp(-x))
> INFO:  training/zedler_0013_010035.bin.png:pie auh Conciones siue Serones. Hemdreich.
> INFO:  training/zedler_0013_010034.bin.png:mgratitudine: de Festis Sasktorum: Kuadragesiuale
> INFO:  training/zedler_0013_010033.bin.png:prg atorio: de Merc atura: de ortilegss: de vitamncka
> INFO:  training/zedler_0013_010036.bin.png:Aquapu lco, Lat. Portus aquæ pulchræ, eine

## Your Environment

* Python version: Python 2.7.13

* Git revision of ocropy: 
downloaded 01.01.2017
* Operating System and version:
Ubuntu 17.04 x64

**Comment by zuphilip** [comment]
We have seen similar errors before and I think https://github.com/tmbdev/ocropy/pull/201 will fix this. You can test these changes locally.

**Comment by rnsrk** [comment]
https://github.com/tmbdev/ocropy/commit/66c6007a218c44845bdd9048228f408d337dd717 worked fine, no runtime warnings anymore

**Comment by kba** [comment]
Fix was merged in #201
