### ISSUE TITLE
Is it possible to train ocropy for any other language?

### ISSUE THREAD

**Issue by codeheadshopon** [tmbdev/ocropy#248]
Basically ta  ocropy is for recognition of english characters but is it possible to use it for any other language?

**Comment by zuphilip** [comment]
Yes, that is possible and besides English there is also the (official) Fraktur model which is trained to another script. Some more models are listed in the wiki: https://github.com/tmbdev/ocropy/wiki/Models

**Comment by zuphilip** [comment]
Maybe just note: Ocropus does not have any language modeling at the moment, the models are for scripts e.g. the letters of a language.

**Comment by codeheadshopon** [comment]
Thank you very much for quick reply.
