### ISSUE TITLE
Regression in ocropus-gpageseg

### ISSUE THREAD

**Issue by jze** [tmbdev/ocropy#251]
The changes between rev 2e83dcb and 8d378ab caused a regression in ocropus-gpageseg. The older version produces a line like this:
![good nrm](https://user-images.githubusercontent.com/765178/31597611-a295fd1c-b249-11e7-872c-1c5d7bb86ec7.png)

With the new version a line includes some pixels from the next line:
![bad nrm](https://user-images.githubusercontent.com/765178/31597606-9d000b04-b249-11e7-8df9-8d1cdf81d662.png)

**Comment by stweil** [comment]
Could you try to narrow it down to the commit which causes the regression by using `git bisect`?

**Comment by jze** [comment]
2e83dcb and 8d378ab are successive commits for `ocropus-gpageseg`

**Comment by stweil** [comment]
Yes, but 8d378ab0e9dd832638c0205149fd2cf6165215b7 merged several commits. How can I reproduce the problem myself?

**Comment by zuphilip** [comment]
Fixed in #252
