### ISSUE TITLE
Updating the wiki

### ISSUE THREAD

**Issue by urhub** [tmbdev/ocropy#256]
I am spending some hours on a class project to update Ocropy documentation.
I would like to collect requests for documentation you want to see in the Wiki.

## Possible Solution

Please add comments here what you would like to see added or changed to the documentation.

**Comment by zuphilip** [comment]
The training in ocropus is currently not documented and it would be great if you can start for that with a new wiki page for that. The recognition is only sparsely described https://github.com/tmbdev/ocropy/wiki/Text-Recognition-RNN and any improvement there would be great as well.

**Comment by urhub** [comment]
Thanks, @zuphilip . I will produce a LibreOffice document first and then look into updating the Wiki. I am hoping to structure the document according to the data flow, roughly:
Table Of Contents
--------------------
Introduction
Ground Truth
Training
Evaluation
Recognition
Results

**Comment by uvius** [comment]
There is a 25 page document from 2015 detailing just that, and it is linked on the Wiki page: [How to train your own models](http://cistern.cis.lmu.de/ocrocis/tutorial.pdf) (you can ignore the reference to the wapper ocrocis and look at the explanations for ocropy).

**Comment by urhub** [comment]
Yes, I have seen the Ocrocis document before. Thanks for the reminder, I will take a look at that again.

**Comment by urhub** [comment]
My document so far is looking more like a tutorial on tips to handle Ocropy. I am hoping to add a quiz for self assessment. I have avoided writing about the algorithms since I don't know which ones are in the latest version and there are other journal papers and thesis works that talk about them. I have borrowed material from other websites and acknowledged them in the Bibliography, including Breuel's block diagrams.
I got a request from my class to use a Creative Commons License so that it can be used freely by others and be part of Open Educational Resources.

**Comment by zuphilip** [comment]
This sounds interesting! I am looking forward to have a look at it.

**Comment by urhub** [comment]
@zuphilip I can send you a copy early if you would like to proof read. There is not a whole lot to it really.

**Comment by urhub** [comment]
Hi all, I have uploaded my document at https://github.com/digiah/oldOCR/blob/master/ocropy_getting_started.pdf. 
Let me know of any corrections or omissions and I will fix it. Thanks.

**Comment by zuphilip** [comment]
At section 7 Recognition:
* You write "Any time a line does not have any characters or no characters is recognized, there is an error produced" which seems to point to issue #243 which should have been fixed by https://github.com/tmbdev/ocropy/commit/f9b50fbf555334ceda50b26eaace72a07d3bfeaf . Do you still see this error?
* The file https://github.com/tmbdev/ocropy/blob/master/ocrolib/chars.py was updated and now also include e.g. Portuguese characters.

VUE Workflow diagram:
* I created this diagram in February 2017.

**Comment by urhub** [comment]
Thanks for those comments, Philipp. Sorry for the delay in making the corrections. I have updated the file with the information you provided and edited the Bibliography on the VUE diagram.

**Comment by iShinJini** [comment]
Hi may i know how to use Ocropus-errs ?
