### ISSUE TITLE
import errors.

### ISSUE THREAD

**Issue by CruzzRazor** [tmbdev/ocropy#263]
i am getting the following error since last 3 days. not able to get rid of this.

'gcc' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:/Users/allud/ocropus_venv/Scripts/ocropus-nlbin", line 15, in <module>
    import ocrolib
  File "c:\python27\Lib\ocrolib\__init__.py", line 12, in <module>
    import common
  File "c:\python27\Lib\ocrolib\common.py", line 34, in <module>
    import lstm
  File "c:\python27\Lib\ocrolib\lstm.py", line 38, in <module>
    import nutils
  File "c:\python27\Lib\ocrolib\nutils.py", line 25, in <module>
    lstm_native = compile_and_load(lstm_utils)
  File "c:\python27\Lib\ocrolib\native.py", line 69, in compile_and_load
    path = compile_and_find(c_string,**keys)
  File "c:\python27\Lib\ocrolib\native.py", line 65, in compile_and_find
    raise CompileError()
ocrolib.native.CompileError
(ocropus_venv)

please help.

**Comment by amitdo** [comment]
ocropy currently depends on gcc.

Check that gcc is installed on your system.

For ocropy team:
The native code can be dropped and replaced by np.einsum(), which is very fast.

**Comment by amitdo** [comment]
I'm not sure if ocropy was ever tested to work on windows.

**Comment by zuphilip** [comment]
a) Ocropy is currently not supported to run on windows directly, also it might work with some hacks. Usually, for windows I would suggest you rather to use this [docker container](https://hub.docker.com/r/kbai/ocropy/). However, some other people tried to run ocropy on windows already, see https://github.com/tmbdev/ocropy/issues/73.

b) @amitdo wrote:
> The native code can be dropped and replaced by np.einsum(), which is very fast.

This sounds interesting. Can you create a PR for this?

**Comment by amitdo** [comment]
>This sounds interesting. Can you create a PR for this?

I will do so :-)

**Comment by amitdo** [comment]
Another possible way to run ocropy on windows:
https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

I didn't try it (I only have Linux)

**Comment by urhub** [comment]
I am running Ocropy on bash for windows 10. It works fine. By default it does not run the GUI and so you cannot see any plots. I am not sure that it can.

**Comment by CruzzRazor** [comment]
solved this issue on windows itself.installed mingw gcc of latest version and compatible with python 
eg. 64 bit mngwgcc on 64 bit python 2.7.14 on 64 bit windows 10. thanks for support
