### ISSUE TITLE
getting typeerror object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by CruzzRazor** [tmbdev/ocropy#267]
i am trying to ./runtest i am getting error saying 

```
$ ./run-test
INFO:  # ./tests/testpage.png
INFO:  === ./tests/testpage.png 1
INFO:  estimating skew angle
INFO:  estimating thresholds
INFO:  rescaling
INFO:  ./tests/testpage.png lo-hi (0.39 1.44) angle  0.1 no-normalization
INFO:  writing
INFO:
INFO:  ########## C:/Users/allud/ocropy/env/Scripts/ocropus-gpageseg temp/????
INFO:
INFO:  temp\0001.bin.png
INFO:  scale 19.493589
INFO:  computing segmentation
INFO:  computing column separators
INFO:  considering at most 3 whitespace column separators
INFO:  computing lines
INFO:  propagating labels
INFO:  spreading labels
INFO:  number of lines 100
INFO:  finding reading order
INFO:  writing lines
INFO:      91  temp\0001.bin.png 19.5 92
INFO:
INFO:  ########## C:/Users/allud/ocropy/env/Scripts/ocropus-rpred -n temp/????
INFO:
INFO:  #inputs: 92
Traceback (most recent call last):
  File "C:/Users/allud/ocropy/env/Scripts/ocropus-rpred", line 120, in <module>
    network = ocrolib.load_object(args.model,verbose=1)
  File "c:\python27\Lib\ocrolib\common.py", line 435, in load_object
    fname = ocropus_find_file(fname)
  File "c:\python27\Lib\ocrolib\common.py", line 625, in ocropus_find_file
    sysconfig.get_config_var("datarootdir"), "ocropus"))
  File "C:\Users\allud\ocropy\env\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\allud\ocropy\env\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
(env)
```

please help.

**Comment by kba** [comment]
Do you have `en-default.pyrnn.gz` in `./models`?

**Comment by CruzzRazor** [comment]
yes i have it. i have downloaded the en-default.pyrnn.gz file from link & pasted it as it is as am using it on windows. do i need to extract it ?

**Comment by kba** [comment]
No, it's a Windows issue, I think

```
sysconfig.get_config_var("datarootdir")
```

returns

```
None
```

in Windows. Can you confirm that, i.e. try 

```sh
python -c 'import sysconfig;print(sysconfig.get_config_var("datarootdir"))'
```

**Comment by CruzzRazor** [comment]
yes it returns none.

**Comment by CruzzRazor** [comment]
so what do i need to do? is it a bug? how can i fix this?

**Comment by kba** [comment]
It's a bug, please merge #268 locally and see if the issue goes away:

```
git fetch origin
git merge origin/windows-sysconfig
```

I'll try it the next time I have access to a Windows machine.

(If you want to just get up and running, comment out https://github.com/tmbdev/ocropy/blob/master/ocrolib/common.py#L624-L625 until #268 is resolved)

**Comment by stweil** [comment]
There exist different Python binaries for Windows. It looks like the official Python releases for Windows neither use cmake nor autotools for building, so those binaries do not know 'datarootdir'. The Python binaries from Cygwin return a valid path.

**Comment by CruzzRazor** [comment]
@kba nope its not working though. i am looking for an OCR engine other than tesseract with good accuracy as its bit urgent. can you please suggest any alternative to ocropy if possible to get the things done for a while.

**Comment by stweil** [comment]
@CruzzRazor, which error do you get now (with the code fix suggested by @kba)?

**Comment by CruzzRazor** [comment]
`$ ./run-test
INFO:  # ./tests/testpage.png
INFO:  === ./tests/testpage.png 1
INFO:  estimating skew angle
INFO:  estimating thresholds
INFO:  rescaling
INFO:  ./tests/testpage.png lo-hi (0.39 1.44) angle  0.1 no-normalization
INFO:  writing
INFO:
INFO:  ########## C:/Users/allud/ocropy/env/Scripts/ocropus-gpageseg temp/????
INFO:
INFO:  temp\0001.bin.png
INFO:  scale 19.493589
INFO:  computing segmentation
INFO:  computing column separators
INFO:  considering at most 3 whitespace column separators
INFO:  computing lines
INFO:  propagating labels
INFO:  spreading labels
INFO:  number of lines 100
INFO:  finding reading order
INFO:  writing lines
INFO:      91  temp\0001.bin.png 19.5 92
INFO:
INFO:  ########## C:/Users/allud/ocropy/env/Scripts/ocropus-rpred -n temp/????
INFO:
INFO:  #inputs: 92
# loading object .\models\en-default.pyrnn.gz
Traceback (most recent call last):
  File "C:/Users/allud/ocropy/env/Scripts/ocropus-rpred", line 120, in <module>
    network = ocrolib.load_object(args.model,verbose=1)
  File "c:\python27\Lib\ocrolib\common.py", line 445, in load_object
    return unpickler.load()
EOFError
(env)`

**Comment by urhub** [comment]
@CruzzRazor, If you are using Windows 10, you could try running Ocropy on bash for windows 10.
https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10
The files you download on windows can be accessed in bash at /mnt/c/path_to_download_directory

> i am looking for an OCR engine other than tesseract with good accuracy as its bit urgent.

**Comment by zuphilip** [comment]
@CruzzRazor This looks like a new issue. Can you open another issue if this persist?
