### ISSUE TITLE
When I want to continue training on the original model，Something wrong happened

### ISSUE THREAD

**Issue by moucmou** [tmbdev/ocropy#278]
I trained a model with clstm and found that the model's training set was too small, so I expanded the training set. Training on the original model issued the following questions!
![image](https://user-images.githubusercontent.com/25379601/34033174-20e06c68-e1b4-11e7-87ed-0403b442cf37.png)
I hope to get your help, thanks

**Comment by zuphilip** [comment]
This look like a clstm issue which would better be asked at https://github.com/tmbdev/clstm/issues .

**Comment by moucmou** [comment]
https://github.com/tmbdev/clstm/issues/106

**Comment by moucmou** [comment]
I think I know how this error happened.However, a large number of character sets can lead to slow training
