### ISSUE TITLE
Creating a training model on cursive hand writing images?

### ISSUE THREAD

**Issue by gjerome5** [tmbdev/ocropy#295]
Hi Guys,
can anyone tell me how to train an ocropus model for hand written text images,
Is there any possibility to do this bros?

**Comment by zuphilip** [comment]
@gjerome5 Your questions are too generic and you can start with the information which can be easily found here in the wiki. Moreover, you didn't react on the answer I gave you in #293. Thus, I will close this issue again soon...

**Comment by zuphilip** [comment]
(continued in #293)
