### ISSUE TITLE
Multithreaded Training

### ISSUE THREAD

**Issue by Programmer888** [tmbdev/ocropy#302]
I it possible to run ocropy training multithreaded like the page segmentation and the preprocessing?
I currently train my models using the command
`ocropus-rtrain -c train/*/*.gt.txt test/*/*.gt.txt -o models/model train/*/*.bin.png`

**Comment by amitdo** [comment]
>it possible to run ocropy training multithreaded

No, it is not possible.

**Comment by ChillarAnand** [comment]
Duplicate of https://github.com/tmbdev/ocropy/issues/166

**Comment by zuphilip** [comment]
I just added a new FAQ for this: https://github.com/tmbdev/ocropy/wiki/FAQ#how-can-the-training-been-speed-up-is-it-possible-to-parallelize-the-trainig-or-to-use-gpu-power-for-training

**Comment by christophered** [comment]
@zuphilip have you tested ocropy2?

**Comment by zuphilip** [comment]
No, I haven't yet tested ocropy2. The best chances to hear more about it is to go to [Vienna next week](https://das2018.cvl.tuwien.ac.at/en/) where @tmbdev is giving a workshop. Maybe there will also be some material shared afterwards online?
