### ISSUE TITLE
question: When to use ocropy-ltrain?

### ISSUE THREAD

**Issue by bugsyb** [tmbdev/ocropy#304]
All tutorials recommend ocropy-rtrain to be used (or clstm) however there is ocropy-ltrain too. 
The latter seems to be a simpler version of rtrain, just going through the source, without that many checks, etc. but the bigger question is when one should use the ltrain version? Or maybe is it left for legacy use reasons (i.e. someone who used to use ltrain doesn't have to adjust to new rtrain use?).

Thanks in advance.

**Comment by mittagessen** [comment]
ocropus-ltrain was a driver for an early version of the clstm library. The python API no longer works (and the one implemented in ltrain doesn't match any stable clstm version) so it isn't useful for anything really.

**Comment by bugsyb** [comment]
Thank you.
