### ISSUE TITLE
Could you recommend some materials about the algorithm you use?

### ISSUE THREAD

**Issue by hsmyy** [tmbdev/ocropy#31]
Hi! I feel this project is very interesting and I want to learn from it.
So could you recommend me some materials(papers or books) you referred in this project?
Thank you very much

**Comment by adnanulhasan** [comment]
There is one paper "High Performance OCR for Printed Latin and Fraktur using LSTM Networks". Please see this paper and references therein to learn more about the recognition engine used in ocropy.

**Comment by hsmyy** [comment]
Thank you very much for your help!

**Comment by nixar** [comment]
It's just a quick google away, but to save everyone 10s, here's a link to the preprint: http://www.cis.uni-muenchen.de/~springmann/papers/2014-04-07-DATeCH2014-Springmann.pdf

**Comment by zuphilip** [comment]
That is a different paper with different authors. Google shows you here a paper refering to the one mentioned above. The official published version can be found on IEEE Xplore: http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6628705

**Comment by nixar** [comment]
Ah yes you're right. I had saved it for later reading and not paid attention. Anyone has a link to a non-paywalled version?

**Comment by adnanulhasan** [comment]
Here is the link of my website to see the pdf version:
https://docs.google.com/a/iupr.com/file/d/0B_81tRo0ZXnLSE9BeGdNcDBXYms/edit

It's a slightly different version, but essentially it is the same paper .

**Comment by adnanulhasan** [comment]
There were multiple requests to share the paper. Here is the link of this paper on Academia:
https://www.academia.edu/3568100/High_Performance_OCR_for_English_and_Fraktur_using_LSTM_Networks
I hope that viewing this paper here will be easier.

**Comment by adnanulhasan** [comment]
This issue is resolved, please close it if you are satisfied. Thanks!

**Comment by tianyaqu** [comment]
I would like to recommend this paper "A Novel Connectionist System for Unconstrained Handwriting Recognition",it explains in every details about the LSTM model and  CTC used in this project.
Here is link of this paper:
www.cs.toronto.edu/~graves/tpami_2009.pdf
Hope it may help.

**Comment by zuphilip** [comment]
We are collecting some publications around ocropus on the wiki page https://github.com/tmbdev/ocropy/wiki/Publications . Everybody can add more publications there, maybe we should also add a more general section about the networks used in the software.
