### ISSUE TITLE
EOFError in return unpickler.load()

### ISSUE THREAD

**Issue by ricardobnjunior** [tmbdev/ocropy#311]
## Expected Behavior

Dear @tmbdev ,
I am having an error when I try to run the archive ocropus-rpred.py on Windows.
I downloaded the archive \en-default.pyrnn.gz, and I send by parse the directory where they are the images (tests\testpage).

## Current Behavior

C:\Users\suporte\Desktop\OCR_TEST\ocropy-master>python2 ocropus-rpred.py --files=tests\testpage
INFO:
INFO:  ########## ocropus-rpred.py --files=tests\testpage
INFO:
INFO:  #inputs: 1
INFO:  en-default.pyrnn.gz
loading object .\.\en-default.pyrnn.gz
Traceback (most recent call last):
  File "ocropus-rpred.py", line 121, in <module>
    network = ocrolib.load_object(args.model,verbose=1)
  File "C:\Users\suporte\Desktop\OCR_TEST\ocropy-master\ocrolib\common.py", line 446, in load_object
    return unpickler.load()
EOFError

## Steps to Reproduce (for bugs)

1.
![image](https://user-images.githubusercontent.com/18532570/44412697-f5ca5200-a53f-11e8-9bb0-1456d501c1b9.png)

2.
3.
4.

## Your Environment

* Python version: 2.7

* Git revision of ocropy: 
* Operating System and version: Windows 10

**Comment by kba** [comment]
I recommend running ocropy on linux in a virtual machine, but see https://github.com/tmbdev/ocropy/issues/12. Might be `gunzip` is not in your path, maybe try @csteelatgburg's [advice](https://github.com/tmbdev/ocropy/issues/12#issuecomment-390774124).

**Comment by ricardobnjunior** [comment]
Thank you. I solved the problem with this answer.
