### ISSUE TITLE
can ocropy give classification of different type of text line?

### ISSUE THREAD

**Issue by DamonsJ** [tmbdev/ocropy#317]
suppose a document page contains text ,math equation and image, can ocropy identify which block is text, which block is math equation, which block is image?

may be there is table in document page ? Is there any solution?

Thanks

**Comment by kba** [comment]
Not part of ocropus, ocropus does line detection with a few heuristics / knobs to turn to avoid lines bleeding across columns or inadvertently merging lines etc.

Have a look at [dhSegment](https://dhlab-epfl.github.io/dhSegment/), for a semi-automatic solution check out [LAREX](http://www.is.informatik.uni-wuerzburg.de/research-tools-download/larex/) (they are working on a trainable pixel classifiier as well IIRC) or the Leptonica toolset which tesseract uses.

**Comment by kba** [comment]
For completeness sake or the curious: https://github.com/tmbdev/ocropy/wiki/OCRopus-File-Formats#physical-layout

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/blob/b502bbf58e78/src/ccstruct/publictypes.h#L53
https://github.com/tesseract-ocr/tesseract/blob/5fdaa479da2c/src/ccmain/pageiterator.h#L225
