### ISSUE TITLE
Model for french medieval manuscript

### ISSUE THREAD

**Issue by y0un35** [tmbdev/ocropy#320]
Hello everyone
i have some old books in french, and i want to try ocropus on it but couldn't find a good model for it!
what should i do?!

**Comment by y0un35** [comment]
> You could try https://github.com/zuphilip/ocropy-french-models or train your own.

I already tried it , but it doesn't work perfectly, the books have an old writing. (if you have another model) thanks in advance.

i have other question too, about dataset, it's not annotated (doesn't have labels) can ocopus do this and then caompute accuracy based on these labels?

**Comment by kba** [comment]
You can also try [kraken](https://github.com/mittagessen/kraken) with e.g. https://github.com/PonteIneptique/toebler-ocr.

**Comment by stweil** [comment]
Your first example works partially with Tesseract and no special training:

    $ tesseract A1_5.jpg - -c user_defined_dpi=300 -l script/Latin --psm 6
    F
    Ea tific ftudiofe lecto? fit i6 libi Fronicarum per
    8 B viam epitbomatis z breuiarj Compila opus jde
     preclarum.z a doctiflimo quoa comparatidum.£ ontinet
    ein gefta. queciqs O1gmo:a funt NOtgtu ab initio mid ad
    banc vígs tepos softri calamitatem, L aftigattigza virs
    doctiffimisvt magis elabdzatum tn lucem prodiret. Adin
    — mut guten T preces P ciii Sebald Schreyer
    Sebaran kamermaili bunc libum domnus Antho
    niys koberger Muren pergeimpzeffit. Adhibitis tamé vé.
    ris matbematicis pingendiqs arte peritiffimis, 191chaele
    ~ wolgemurerwilbelmo Pleydemwurff.quarii fotera anv
     Siflmagsanimaduerfore mm auam a
    “prrozumfigureinferte funt. £onfummatu gutci) oyode”
    sia menfis 3ulý Zinno BIOS KÉCtA93
    E S A sa i n

**Comment by y0un35** [comment]
@stweil without training and it works! so someone else already did the job.
thanks,
but what about ocropus? i like to try it to! how can i do it?!
also, is there a function in ocropus that show me the accuracy and errors also plot them?

thanks again

**Comment by kba** [comment]
@y0un35 I think you've received some pointers and links, feel free to open a new issue for further questions.
