### ISSUE TITLE
How does it apply to java

### ISSUE THREAD

**Issue by WangBoWang** [tmbdev/ocropy#331]
How does it apply to java

**Comment by kba** [comment]
Hard to say Unless you elaborate a bit what you mean. Not at all? Both ocropy and Java are software? OCR software can be used in Indonesia?

**Comment by WangBoWang** [comment]
We need to implement simple identification of local images in Java, and we want to find a project similar to tess4J that can be used for local API calls.Do you support Java native API calls?

**Comment by kba** [comment]
> Do you support Java native API calls?

No. Jython might be an option while we're still at 2.7. Haven't tried though.

If tess4j bindings are up-to-date, I'd recommend that, since tesseract 4+ uses similar technologies and is actively developed.

**Comment by WangBoWang** [comment]
Ok. Thank you very much for your help.
