### ISSUE TITLE
Please provide  en-default.pyrnn.gz and fraktur.pyrnn.gz models

### ISSUE THREAD

**Issue by anshsingh1000** [tmbdev/ocropy#41]
http://www.tmbdev.net is not accessiable.

It would be great if en-default.pyrnn.gz and fraktur.pyrnn.gz models can be bundled with the code

**Comment by jplethier** [comment]
I am trying get these two models too

**Comment by danvk** [comment]
You can get `en-default.pyrnn.gz` from #42 in the meantime.

**Comment by jplethier** [comment]
Thanks @danvk

**Comment by tmbdev** [comment]
The file is, unfortunately, a little too large to put into the repository.

I'm not quite sure why the saved models are so large; the equivalent clstm models are less than 1Mbyte.

**Comment by kba** [comment]
@CBien managed to reduce the size of the models drastically here https://github.com/CBien/ocropy/commit/151a09dc269961b0c6362f67b0808493cd99144d

**Comment by zuphilip** [comment]
Yes, see also #100 . BTW are the standards models already available in the smaller size?

**Comment by hardikjoshi51** [comment]
How do we use these models. While installing OCRopus using setup.py it is throwing erro "You must download the default model 'en-default.pyrnn.gz'".

After downloading how do we use these models to remove the error.
