### ISSUE TITLE
Install guide for fedora

### ISSUE THREAD

**Issue by tobimensch** [tmbdev/ocropy#48]
Hello,

not sure this is a valid issue, so please just close it, if not.

But could someone add a description how to install everything on fedora?

I tried it and they're obviously not using exactly the same package names,
since I couldn't install the requirements with yum/dnf or even pip.

Or even just a confirmation that someone got it running on fedora would be nice.

**Comment by QuLogic** [comment]
```
curl scipy python-matplotlib python-tables firefox ImageMagick opencv-python python-BeautifulSoup
```
or
```
curl python3-scipy python3-matplotlib python3-tables firefox ImageMagick python3-beautifulsoup4
```
(though this fork doesn't work on Python 3. And OpenCV isn't available at the moment.)

**Comment by zuphilip** [comment]
Add a link from the FAQs to here: https://github.com/tmbdev/ocropy/wiki/FAQ#how-to-install-ocropus-on-fedora
