### ISSUE TITLE
FloatingPointError while training

### ISSUE THREAD

**Issue by lesliekim** [tmbdev/ocropy#49]
I followed the "run-rtrain" document to train RNN. I got the training set by " tar -zxf tests/uw3-500.tgz".  I didn't change anything, neither RNN structure nor parameters. I meet the following problem while training: FloatingPointError: overflow encountered in exp. However, the program does not stop. It keeps iterating while showing the above FloatingPointError message again and again. 
I reduce the learning rate to half of the default value. But the same problem occurs. Do I train the network in the wrong way?

**Comment by tmbdev** [comment]
The default parameters should work without problems. Can you say more about your environment (Python version, OS, compiler version, etc.)?

You might want to give CLSTM a try as well; it's the same algorithm in C++.

**Comment by lesliekim** [comment]
My environment: python 2.7.6  
                           Ubuntu 14.04.1 LTS \n \l
                           gcc version 4.8.4

**Comment by fafo** [comment]
I'm getting the same errors. I've tried clipping the values, but the model seems keeping very high error rates (I'm experimenting with training samples taken from a mobile camera, since we want to recognize receipts uploaded with mobiles)

def ffunc(x):
    "Nonlinearity used for gates."
    # cliping to avoid overflows
    return 1.0/(1.0+exp(clip(-x, None, 700)))

**Comment by tmbdev** [comment]
Sorry for not responding earlier. Can you provide a backtrace?

You might also add a line of python to the main program to turn overflows into errors (when I get around to it, I may do this myself).

**Comment by zuphilip** [comment]
Should be fixed with #201.
