### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by braddockcg** [tmbdev/ocropy#55]
On some images, rpred and rtrain's dewarp function throws an error because the padding is insufficient.  This seems to be particularly true of images which have borders or other noise near the top and bottom edges.  Attached is an example.

![ocropy-bug-example](https://cloud.githubusercontent.com/assets/1967740/9670848/877f2cb4-5243-11e5-9319-636579225aac.png)

I have a simple, but unsatisfying, fix for this where I double the amount of padding.  See my github fork commit (branch bugfix) at:
https://github.com/braddockcg/ocropy/commit/be2e6d1e996b75898ff0958fc680c995b2574e4d

The full error is:

Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rpred", line 245, in safe_process1
    return process1(arg)
  File "/usr/local/bin/ocropus-rpred", line 145, in process1
    line = lnorm.normalize(line,cval=amax(line))
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lineest.py", line 59, in normalize
    dewarped = self.dewarp(img,cval=cval,dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lineest.py", line 56, in dewarp
    dewarped = array(dewarped,dtype=dtype).T
ValueError: setting an array element with a sequence.

**Comment by tmbdev** [comment]
Thanks; I'll look into this again soon, when I get around to cleaning up some of this code.

**Comment by zuphilip** [comment]
The picture is a color image and it should be just a black/white picture. If you are binarize the picture, then the `ocropus-rpred` is working as it should. It looks that the check, which should prevent that case, is not working correctly.

**Comment by zuphilip** [comment]
While my comment above is true, it seems that this is more like some coincident and a real fix should somehow increase the padding. I created now another PR #133 extending your idea, which will solves this issue then.

**Comment by zuphilip** [comment]
Closed by #133
