### ISSUE TITLE
ocropus-gpageseg - Segmentation

### ISSUE THREAD

**Issue by NatsuSencho** [tmbdev/ocropy#57]
I'm from Thailand, and I use OCRopus to recognition my language structure, It's work!
but I got some problem in part of segmentation, for Thai structure have upper and lower character (not related to middle line)
your segmentation have cut some part of upper Thai character. I attempt to adjust argument value.
It still not work. can you tell me about how to add a upper height of the upper line or guild me a part of code that i can edit.

![screenshot from 2015-09-23 22 44 26](https://cloud.githubusercontent.com/assets/11757762/10050081/b63da7c2-6244-11e5-801f-5ebf699f2db7.png)

the upper character is cut
![screenshot from 2015-09-23 22 43 29](https://cloud.githubusercontent.com/assets/11757762/10050082/b66b9ff6-6244-11e5-8663-27373bad51dc.png)

**Comment by NatsuSencho** [comment]
or if you have some document for line segmentation in OCRopus

**Comment by kungfujam** [comment]
Check out this blog for information about line segmentation
http://www.danvk.org/2015/01/09/extracting-text-from-an-image-using-ocropus.html.
There's no documentation other than that you can find in code comments.

**Comment by tmbdev** [comment]
Thanks for providing the link and the info! Is it OK to add it to the home page?

(There used to be some iPython notebook files in the distribution; I'll try to update them and re-add them.)

**Comment by kungfujam** [comment]
I'm sure Dan wouldn't mind. @danvk OK for Tom to add your blog to homepage?

**Comment by danvk** [comment]
yep, no complaints here!

**Comment by zuphilip** [comment]
Both blog posts by @danvk are now linked from the wiki: https://github.com/tmbdev/ocropy/wiki together with some other links to resources and more information. Thank you very much!

**Comment by amitdo** [comment]
Is there something that actually solve the original problem?

**Comment by zuphilip** [comment]
Well, it is hard to say at the moment. I think we would need to have the complete document to look closer at what is going on. @NatsuSencho If you are still interested in this question, then please just reopen this issue or maybe also start a new one.

**Comment by amitdo** [comment]
From Tesseract V3.04.00 release notes:
>Major change to improve layout analysis for heavily diacritic languages: Thai, Vietnamese, Kannada, Telugu etc.

So it seems that these languages are harder to segment and need special code to do it properly.
