### ISSUE TITLE
Cannot run the tests on OS X Yosemite

### ISSUE THREAD

**Issue by nyxz** [tmbdev/ocropy#58]
### Problem

I am following the [installation guide](https://github.com/tmbdev/ocropy/blob/master/README.md) with installed virtualenv and managed to install requirements 1 and 2 successfully. The next step is to run the tests but I cannot execute them. First: simply running `./run-test` fired `zsh: Command ocropus-nlbin cannot be found` or something like that so I changed the script as follows: 

```
#!/bin/zsh -e

rm -rf temp
./ocropus-nlbin tests/testpage.png -o temp
./ocropus-gpageseg 'temp/????.bin.png'
./ocropus-rpred -n 'temp/????/??????.bin.png'
./ocropus-hocr 'temp/????.bin.png' -o temp.html
./ocropus-visualize-results temp
./ocropus-gtedit html temp/????/??????.bin.png -o temp-correction.html

echo "to see recognition results, type: firefox temp.html"
echo "to see correction page, type: firefox temp-correction.html"
echo "to see details on the recognition process, type: firefox temp/index.html"
```

Then it found the commands I guess but `./run-test` caused the following error to occur:

```
clang: warning: -O4 is equivalent to -O3
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "./ocropus-nlbin", line 9, in <module>
    import ocrolib
  File "/Users/nyxz/dev/workspace/python/ocropy/ocrolib/__init__.py", line 12, in <module>
    from common import *
  File "/Users/nyxz/dev/workspace/python/ocropy/ocrolib/common.py", line 18, in <module>
    import lstm
  File "/Users/nyxz/dev/workspace/python/ocropy/ocrolib/lstm.py", line 32, in <module>
    import nutils
  File "/Users/nyxz/dev/workspace/python/ocropy/ocrolib/nutils.py", line 25, in <module>
    lstm_native = compile_and_load(lstm_utils)
  File "/Users/nyxz/dev/workspace/python/ocropy/ocrolib/native.py", line 67, in compile_and_load
    path = compile_and_find(c_string,**keys)
  File "/Users/nyxz/dev/workspace/python/ocropy/ocrolib/native.py", line 63, in compile_and_find
    raise CompileError()
ocrolib.native.CompileError
```
### Previous steps

To make the requirements install successfully I needed to install some additional stuff. I will list everything that I had to install here:
- pip
- python3
- virtualenv
- hdf5
- pylab

I use ZSH as you may already noticed. I don't know what impact this has on the installation so I am just mentioning it.

Any suggestion on how to finish the installation with test running normally are highly appreciated!

**Comment by amitdo** [comment]
Check this:
https://github.com/tmbdev/ocropy/blob/master/README_OSX.md

clang 3.7 has openmp support.
http://llvm.org/releases/3.7.0/tools/clang/docs/ReleaseNotes.html#openmp-support

You mentioned python3, but ocropy only supports python 2.7.

http://llvm.org/releases/3.7.0/tools/clang/docs/ReleaseNotes.html#openmp-support

**Comment by nareshganesan** [comment]
I was facing similar issue in OS X 10.11 python 2.7. 
Thanks for the OS X clang patch info.
It solved my issue.

**Comment by amitdo** [comment]
:-)

**Comment by nachtgold** [comment]
I had executed `sudo python setup.py install` after removing the `f` character from the fopenmp parameter, but then `./run-test` worked.

**Comment by kba** [comment]
The problem here is that apparently (cannot test) clang on OSX specifies the openMP flag as `-openmp` not `-fopenmp`.

If you don't run `sudo python setup.py install`, the binaries won't be available on your `$PATH` so the test runner will complain about `ocropus-*` being an unknown command. `sudo python setup.py install` is the standard mechanism to install python projects system-wide.

We should probably merge the OSX README into the main readme.

**Comment by amitdo** [comment]
>The problem here is that apparently (cannot test) clang on OSX specifies the openMP flag as -openmp not -fopenmp.

clang 3.7
http://llvm.org/releases/3.7.0/tools/clang/docs/ReleaseNotes.html#openmp-support

clang 3.8
http://llvm.org/releases/3.8.0/tools/clang/docs/ReleaseNotes.html#openmp-support-in-clang

**Comment by kba** [comment]
@amitdo Thanks for the links, but I still don't understand why the fix in https://github.com/tmbdev/ocropy/blob/master/README_OSX.md would work (`-openmp` instead of `-fopenmp`).

That being said, it would probably best to find a better option instead of dynamically compiling C code, maybe ctypes or cffi?

**Comment by amitdo** [comment]
>I still don't understand why the fix in https://github.com/tmbdev/ocropy/blob/master/README_OSX.md would work (-openmp instead of -fopenmp).

This was written for clang version<3.7. It looks like` -openmp` is ignored => the code will compile but without openmp support. I think that `-fopenmp` was recognized by some older versions of clang, but unlike the newer versions, the openmp library was not official part of llvm, but a separate project and package and was considered experimental.
https://clang-omp.github.io/

**Comment by amitdo** [comment]
http://stackoverflow.com/questions/37321840/clang-via-homebrew-llvm38-compile-error-with-system-includes
