### ISSUE TITLE
Understanding ocropy installation

### ISSUE THREAD

**Issue by hendk** [tmbdev/ocropy#60]
Hello everyone,

I'm working on a project and need to use ocropy, I tried to install it on windows but failed, so I moved to Ubuntu. I'm not a nerdy when it comes to Ubuntu, so I'm stuck now. 

I have installed python 2.7 on Ubuntu and all the requirements 1 and 2, also I've installed opencv.

Then I tried to install ocropy as written in the read-me but failed at this line:
mv en-default.pyrnn.gz models/ 

I actually don't understand it, because its previous line gets a .gz then we want to move it to a model directory (which is not created yet!) then we need to run setup.py which is not their. So I don't know if I'm missing something, I know I might sound so ignorant to some of you but I'm really new to this and I'm doing my best to understand, I also didn't find any helpful information on the net regarding my issue.

Any help is appreciated, Thank you in advance.

**Comment by zuphilip** [comment]
The first thing which you have to do is to clone (copy) all files from github to your local machine, i.e.
```
$ git clone https://github.com/tmbdev/ocropy.git
```
This will create the directory `models` and the script `setup.py` and also the `PACKAGES` list.

**Comment by hendk** [comment]
@zuphilip  Thank you very much! it is working now
