### ISSUE TITLE
Where can I find source code for previous Ocropus?

### ISSUE THREAD

**Issue by michaelyin** [tmbdev/ocropy#61]
The http://code.google.com/p/ocropus is not available any more. I am reading a few papers related to the old Ocropus, and want to take a look of the code.

**Comment by amitdo** [comment]
ocropus 0.4.4
http://ocroold.ocropus.googlecode.com/hg/

page segmentation code:
http://ocrorast.ocropus.googlecode.com/hg/

line segmentation code:
http://ocrolseg.ocropus.googlecode.com/hg/

language model code:
http://ocrofst.ocropus.googlecode.com/hg/

**Comment by michaelyin** [comment]
Thanks for the info. How about version 0.5 and 0.6?

**Comment by amitdo** [comment]
Search the commit history of ocropy:
https://github.com/tmbdev/ocropy/commits/master

Releases dates:
0.5  04/2012
0.5.x  05-07/2012
0.6  08/2012

**Comment by michaelyin** [comment]
I check out code 0.4.4 of ocropus. Most of the code are in C++, and the ocropy repository are all python code.  It is kind of a surprise to me. I thought version 0.5 should not a big change from version 0.4.4. 

But thanks for the info.

**Comment by kba** [comment]
I copied @amitdo's answer to [the wiki](https://github.com/tmbdev/ocropy/wiki/Older-versions) so it's easier to find, feel free to expand.

**Comment by amitdo** [comment]
The google code links are broken now.(

The OP has forked ocropus 0.4.4:
https://github.com/michaelyin/ocropus-git
