### ISSUE TITLE
multi-language documents

### ISSUE THREAD

**Issue by mshanak** [tmbdev/ocropy#62]
hello
can ocropy support multi-language text in the same document( image) ?

**Comment by amitdo** [comment]
Check this paper:

Ul-Hasan, Breuel
Can we build language-independent OCR using LSTM networks?
August 2013

[website is currently down]
http://iupr1.cs.uni-kl.de/~shared/publications/2013-ul-hasan-icdar-can-we-build-lanugage-independent-ocr-using-lstm-networks.pdf

**Comment by adnanulhasan** [comment]
That link is permanently down. However, you can see the paper at 
https://www.researchgate.net/publication/260341307_Can_we_build_language-independent_OCR_using_LSTM_networks
