### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jasonhamilton** [tmbdev/ocropy#64]
Is there any sort of documentation on using the software and an overview of how it works for a new user?  Perhaps there is already a work in progress?  I would be willing to help write some basic documentation if that is of interest.

**Comment by amitdo** [comment]
See here:
http://www.danvk.org/2015/01/09/extracting-text-from-an-image-using-ocropus.html
http://www.danvk.org/2015/01/11/training-an-ocropus-ocr-model.html

**Comment by jasonhamilton** [comment]
Those links are very helpful.  I assume there is no official documentation for the project.  Would the repo maintainer/owner be interested in accepting a pull request for some basic documentation, including an overview of the project's modules and functionality?

I think it would be helpful for the project.  As someone who approached the project, having no understanding of it, it took me a few hours of poking around the code and Googling just to figure out what everything does.

I would be more than happy to contribute the documentation for the project given how amazing the software is.

**Comment by amitdo** [comment]
It seems that right now the developer of this project is focusing on another project - clstm, which is a c++ port of ocropy.

* https://github.com/tmbdev/clstm

**Comment by timClicks** [comment]
FWIW, more documentation would be very useful @jasonhamilton  - even if you host it yourself somewhere for the time being.

**Comment by zuphilip** [comment]
Note: there are some "old" IPython Notebooks in the folder OLD which may also be useful for documentation or technical details, e.g. https://github.com/tmbdev/ocropy/blob/master/OLD/ocropus-steps.ipynb . However, as the folder name indicates, they may be old and deprecated...

**Comment by zuphilip** [comment]
@tmbdev Would it be okay for you if we would start a (community) documentation? I would suggest to use your wiki here: https://github.com/tmbdev/ocropy/wiki which is by default open for everybody to edit.

**Comment by zuphilip** [comment]
We started to use the wiki https://github.com/tmbdev/ocropy/wiki for several things and currently we have the following wiki pages:
 * [Home](https://github.com/tmbdev/ocropy/wiki)
 * [Compute errors and confusions](https://github.com/tmbdev/ocropy/wiki/Compute-errors-and-confusions)
 * [Models](https://github.com/tmbdev/ocropy/wiki/Models)
 * [Older versions](https://github.com/tmbdev/ocropy/wiki/Older-versions)
 * [Publications](https://github.com/tmbdev/ocropy/wiki/Publications)
 * [Working with Ground Truth](https://github.com/tmbdev/ocropy/wiki/Working-with-Ground-Truth)

Feel free to join us, @jasonhamilton (and everybody else). Adding more technical documentations or (abstract) overview of the modules is very welcome and appreciated!
