### ISSUE TITLE
differences in Softmax implementation with clstm (separate-derivs branch)

### ISSUE THREAD

**Issue by rctay** [tmbdev/ocropy#69]
How does `W2` and `DW2` in ocropy's [python Softmax implementation](https://github.com/tmbdev/ocropy/blob/master/ocrolib/lstm.py#L287) relate to `W` and `w` in the C++ implementation [in clstm](https://github.com/tmbdev/clstm/blob/separate-derivs/clstm.cc#L462)?

**Comment by tmbdev** [comment]
The Python implementation computes matmul(W2, [1, x]); the separate-derivs implementation computes matmul(W, x) + w. So, the first row of W2 is w, and the rest of W2 is W.

Note that the current implementation is here https://github.com/tmbdev/clstm/blob/master/clstm_compute.cc#L282

**Comment by rctay** [comment]
Thanks Tom, I figured that out.

Actually, I have managed to get clstm to match ocropy almost position-for-position, in terms of matrix computations, after tweaking clstm's gaussian filter, uniform filter, etc etc. But I'm stuck at the last bit, the "decoding" - clstm gives a different length of sequence/characters.

**Comment by tmbdev** [comment]
The decoding algorithm is different, so it's not surprising that it would give different results. I don't know which one works better. For OCR it probably doesn't make a big difference, but for other applications, you may want to construct a better decoder.
