### ISSUE TITLE
plan for supporting CUDA  or OpenCL?

### ISSUE THREAD

**Issue by Adesun** [tmbdev/ocropy#72]
Hello,
Currently I'm training a big model, It seems that the learning is kind of slow without gpu.
Do you have some plan for supporting CUDA or OpenCL?
Thanks!

**Comment by amitdo** [comment]
@tmbdev is working on clstm, which will support CUDA and OpenMP.
https://github.com/tmbdev/clstm

**Comment by Adesun** [comment]
@amitdo  thanks, I got it !
