### ISSUE TITLE
Unable to install on windows...  wtf is 'source'?

### ISSUE THREAD

**Issue by enjoysmath** [tmbdev/ocropy#73]
The virtualenv/ stuff seems to instlall, but wtf is 'source'? as in:

source ocropus_venv/bin/activate

Can't do it!  Can't find it - try finding something called source on google. Can't be done.  wtf, over....

**Comment by elgehelge** [comment]
try to google virtualenv ;)

**Comment by dubielt1** [comment]
I was able to successfully install, with a little googling. 

Just download Python, add it to your path, then use `pip install

**Comment by zuphilip** [comment]
Alternatively you can use the docker container: https://hub.docker.com/r/kbai/ocropy/ resp. https://github.com/kba/docker-ocropy

**Comment by zuphilip** [comment]
(FAQ links now here.)

**Comment by karelin** [comment]
One more recommendation is to use Anaconda - the scientific Python distribution, which already contains all necessary libraries, though numpy/scipy will be without MKL (in free version).
