### ISSUE TITLE
how to get the confidence of predicted output ?

### ISSUE THREAD

**Issue by Adesun** [tmbdev/ocropy#74]
Hello,
how to get the confidence of predicted output ?
any advice will be welcomeed. thanks in advance !
Best regards,
Thanks!

**Comment by amitdo** [comment]
See #47 and #25.
See also: http://www.danvk.org/2015/01/09/extracting-text-from-an-image-using-ocropus.html

**Comment by tmbdev** [comment]
Look at CLSTMOCR::predict in clstmhl.h
