### ISSUE TITLE
Error "expected a segmentation image" in ocropus-gpageseg with uint64

### ISSUE THREAD

**Issue by lihan** [tmbdev/ocropy#77]
OS: OS X El Captain. 
```
 ./ocropus-gpageseg 'book/0001.bin.png'
INFO:  
INFO:  ########## ./ocropus-gpageseg book/0001.bin.png
INFO:  
INFO:  book/0001.bin.png
INFO:  scale 41.701318924
INFO:  computing segmentation
INFO:  computing column separators
INFO:  computing lines
INFO:  propagating labels
Traceback (most recent call last):
  File "./ocropus-gpageseg", line 423, in safe_process1
    process1(job)
  File "./ocropus-gpageseg", line 379, in process1
    segmentation = compute_segmentation(binary,scale)
  File "./ocropus-gpageseg", line 320, in compute_segmentation
    llabels = morph.propagate_labels(boxmap,seeds,conflict=0)
  File "/Users/lihanli/projects/ocropy/ocrolib/toplevel.py", line 209, in argument_checks
    raise e
CheckError: 
CheckError for argument labels of function <function propagate_labels at 0x1095f5578>
<ndarray-7ff76272e160 (5753, 4304) uint64 [0,168]> of type <type 'numpy.ndarray'>: expected a segmentation image
```

**Comment by tmbdev** [comment]
The types image morphology functions accept in NumPy depend on the platform and version of Python. You could try using a different Python implementation (e.g., Anaconda). Alternatively, you need to track down what is going on with the types and submit a patch (please make sure to do so in a way that doesn't break it on other platforms).

**Comment by tonothan** [comment]
I'm also on OSX El Capitan and I'm getting a pretty similar error: 

ocropus-gpageseg -n --maxcolseps 0 book/0001.bin.png 
INFO:  
INFO:  ########## /usr/local/bin/ocropus-gpageseg -n --maxcolseps 0 book/0001.
INFO:  
INFO:  book/0001.bin.png
INFO:  scale 18.3303027798
INFO:  computing segmentation
INFO:  computing column separators
INFO:  computing lines
INFO:  propagating labels
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-gpageseg", line 423, in safe_process1
    process1(job)
  File "/usr/local/bin/ocropus-gpageseg", line 379, in process1
    segmentation = compute_segmentation(binary,scale)
  File "/usr/local/bin/ocropus-gpageseg", line 320, in compute_segmentation
    llabels = morph.propagate_labels(boxmap,seeds,conflict=0)
  File "/Library/Python/2.7/site-packages/ocrolib/toplevel.py", line 209, in argument_checks
    raise e
CheckError: 
CheckError for argument labels of function <function propagate_labels at 0x1079f79b0>
<ndarray-7ff34a9ad4c0 (561, 716) uint64 [0,12]> of type <type 'numpy.ndarray'>: expected a segmentation image

Is that the same issue ? Thanks for your help!

Antonia

**Comment by zuphilip** [comment]
It looks for me that the problem here is also a test for integer values which does not yet know `uint64`. I try to add fix similar to https://github.com/tmbdev/ocropy/commit/9be1ae0eeae8772316fc5c3f354e44d3bf98089c but i cannot test on OS X El Captain.

**Comment by zuphilip** [comment]
@lihan @tonothan Please test whether the PR #285 fixes the issue here for you.

**Comment by zuphilip** [comment]
Should be fixed now.
