### ISSUE TITLE
Python-based ocropy faster than c++ version

### ISSUE THREAD

**Issue by crazylyf** [tmbdev/ocropy#78]
Hello,
When I training text-line recognizer, I found Python-based ocropy is even faster than c++ version (on Red Hat 4.4.7, using ocropus-ltrain). This is very strange, as it is said CLSTM is faster than ocropy. Has anyone found the same phenomenon? What is the reason behind this?
Best,
Thanks!

**Comment by amitdo** [comment]
Compile clstm llke this:

> scons usemat=1
sudo scons usemat=1 install

With the 'usemat' option clstm will run much faster.

**Comment by amitdo** [comment]
No longer relevant with the latest clstm master.
