### ISSUE TITLE
package PIL required

### ISSUE THREAD

**Issue by donnut** [tmbdev/ocropy#82]
I noticed that I needed to install `pil` when running  `ocropus-linegen`. Should this be included in requirements_1.txt?

**Comment by donnut** [comment]
Oops, installing `pil` wasn't a good idea. After that `ocropus-nlbin` throws an error:
```
Traceback (most recent call last):
  File "./ocropus-nlbin", line 10, in <module>
    import ocrolib
  File "/home/donnut/dev/python/ocropy/ocrolib/__init__.py", line 12, in <module>
    from common import *
  File "/home/donnut/dev/python/ocropy/ocrolib/common.py", line 176, in <module>
    import PIL
ImportError: No module named PIL
```
Is there some kind of package conflict? After creating the virtual environment (conda) from scratch, without installing the `pil` package, `ocropus-nlbin` works again

**Comment by mittagessen** [comment]
PIL doesn't install from PyPi and AFAIK isn't actively maintained anymore. pillow,the fork everybody is using now, is contained in the requirements file.

**Comment by donnut** [comment]
Issue seems to be solved. I'm using conda (on Arch Linux) as a virtual environment. Recreating the environment and install ocropy worked. The only hiccup is an missing numpy.distutils.core when `Building wheels for collected packages: scipy, numexpr, Cython` but `run-test` is working.
