### ISSUE TITLE
How can I speed up the training process using GPU or multi thread on CPU?

### ISSUE THREAD

**Issue by Halfish** [tmbdev/ocropy#83]
When I am trying to train the ocropy to recognize over 2000 Chinese Character with 800 hidden units, it seems that the training process is really slow. I wonder how can I adjust the model to train it on the GPU or at least use multi threads on CPU.

**Comment by mittagessen** [comment]
That's currently not possible using the python LSTM implementation. Have a look at [clstm](https://github.com/tmbdev/clstm).

**Comment by amitdo** [comment]
Here is report about training clstm to recognize Japanese:

tmbdev/clstm/issues/49

> After 50 days of training on my MacBookPro, 130000 iterations, against 3877 classes of characters, the clstm has achieved 3.6% error rate so far... The hidden nodes is 800, The trained data is 58.2MB.
