### ISSUE TITLE
Project name and spelling: ocropus vs. ocropy vs. OCRopus vs. OCRopy?

### ISSUE THREAD

**Issue by kba** [tmbdev/ocropy#97]
What is the preferred name of this project?

It started as `OCRopus`, then it was mostly used in the lowercase form `ocropus` and at some point the project was renamed `ocropy`, but not the binaries nor the documentation.

Personally, I think (lowercase) `ocropus` is a great name and I would stick with it. It's easy to remember, triggers associations and could even be used for a logo at some point. :smile:

But`ocropy` also works for me, if there are any reasons for the change. Renaming the binaries to `ocropy-...` might break a lot of running code though.

But I do think that spelling should be consistent to get better outreach.

**Comment by wanghaisheng** [comment]
ocropus  +1

**Comment by zuphilip** [comment]
I have already seen a logo for ocropus:
![ocropus](http://madm.dfki.de/_media/ocropus.png)

**Comment by wanghaisheng** [comment]
where d u find it

**Comment by zuphilip** [comment]
Logo found on http://madm.dfki.de/demos/document-analysis

However, any words from @tmbdev could clarify why there are two names and how to continue.

**Comment by amitdo** [comment]
I don't think 'OCRopy' name has ever been used.

IIRC, Thomas Breuel has trademarked 'OCRopus' (or 'ocropus', not sure).

**Comment by amitdo** [comment]
Correcting myself. 'OCRopy' has been used here by Tom.
https://github.com/tmbdev/ocropy/releases/tag/v1.0

**Comment by kba** [comment]
From conversation with @tmbdev: the reasoning is that the whole toolset or system is ocropus and this repository that implements a subset of the tools in Python is called ocropy. ocropus encompasses at least ocropy and clstm, hocr-tools(?), the docker container(?)...

**Comment by tmbdev** [comment]
Well, there used to be a high level repository that included the others as subrepos and contained a top-level driver and build script. But that was several projects, version control systems, and hosting companies ago.

There is currently an ocropus project on github, but it's almost empty.

For now, Kraken has been fulfilling the need for a turnkey system for some people.

I think it's worth revisiting this question once the new GPU code is ready.

**Comment by zuphilip** [comment]
=> moved to FAQ https://github.com/tmbdev/ocropy/wiki/FAQ#what-is-the-preferred-name-of-this-project
