### ISSUE TITLE
New wiki page - Publications

### ISSUE THREAD

**Issue by amitdo** [tmbdev/ocropy#99]
It links to some papers written by Prof. Thomas Breuel (the author of ocropy and clstm) and other people that were his students.

Enjoy! :)

**Comment by zuphilip** [comment]
That looks interesting! Here is the link https://github.com/tmbdev/ocropy/wiki/Publications

**Comment by amitdo** [comment]
Hi @kba and @zuphilip !
I have a link to a paper describing version 0.6 of ocropus/ocropy.
Should I add it to the 'Publications' wiki page? Here is the link:
http://biglearn.org/2012/files/papers/biglearning2012_submission_10.pdf

**Comment by kba** [comment]
@amitdo I don't see why not :+1:

**Comment by amitdo** [comment]
Done! :)

**Comment by amitdo** [comment]
@tmbdev. Tom, you and your students published many papers about page segmentation methods over the years. Is one of them implemented in `ocropus-gpageseg`?

**Comment by tmbdev** [comment]
Yes, ocropus-gpageseg combines a number of those ideas. Note that gpageseg has always been intended only as a temporary solution; a better way of performing page segmentation is via deep learning. We had started on that in my group, but machines were still pretty slow and I got busy with other projects. I'm revising that now using GPUs and multidimensional LSTMs.
